// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Client.SS220.Experience.UiElements;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Mind;
using Content.Shared.Roles;
using Content.Shared.SS220.Experience;
using Microsoft.CodeAnalysis;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using YamlDotNet.Core.Tokens;

namespace Content.Client.SS220.Experience.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExperienceRedactorWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private Dictionary<int, KnowledgePrototype> _cachedIndexedKnowledge = new();

    private readonly LocId _noJobName = "experience-redactor-no-job-name";
    private readonly LocId _noAntagRoleName = "experience-redactor-no-antag-name";

    public ExperienceRedactorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var metadataQuery = _entityManager.GetEntityQuery<MetaDataComponent>();
        var experienceEntities = _entityManager.EntityQueryEnumerator<ExperienceComponent>();
        while (experienceEntities.MoveNext(out var uid, out var _))
        {
            ExperienceEntityOption.AddItem(metadataQuery.TryComp(uid, out var metaDataComponent) ? metaDataComponent.EntityName : uid.ToString(), uid.Id);
        }

        _cachedIndexedKnowledge = _prototype.EnumeratePrototypes<KnowledgePrototype>()
            .OrderBy(x => Loc.GetString(x.KnowledgeName))
            .Select((x, index) => new { Index = index, Proto = x })
            .ToDictionary(x => x.Index, x => x.Proto);

        foreach (var (key, proto) in _cachedIndexedKnowledge)
        {
            KnowledgeOption.AddItem(Loc.GetString(proto.KnowledgeName), key);
        }
    }

    public void SelectEntity(EntityUid uid)
    {
        // TODO: this kinda should be somehow managed and not just return
        if (!_entityManager.TryGetComponent<ExperienceComponent>(uid, out var experience))
            return;

        // TODO: handling like ask to reload or smth
        if (!ExperienceEntityOption.TrySelectId(uid.Id))
            return;

        PopulateCharacterInfo(uid);
        PopulateExperienceVerification((uid, experience));

    }

    private void PopulateCharacterInfo(EntityUid uid)
    {
        CharacterName.SetMessage(_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData) ? metaData.EntityName : uid.Id.ToString());

        if (!_entityManager.System<SharedMindSystem>().TryGetMind(uid, out var mindId, out var mindComponent))
            return;

        var roles = _entityManager.System<SharedRoleSystem>().MindGetAllRoleInfo(mindId);

        if (roles.Count == 0)
            return;

        var job = roles.Any(x => !x.Antagonist);
        var antag = roles.Any(x => x.Antagonist);

        var jobName = job ? roles.First(x => !x.Antagonist).Name : Loc.GetString(_noJobName);
        var antagName = antag ? roles.First(x => x.Antagonist).Name : Loc.GetString(_noAntagRoleName);

        OccupationName.SetMessage(jobName);
        AntagName.SetMessage(antagName);
    }

    private void PopulateExperienceVerification(Entity<ExperienceComponent> entity)
    {

    }

}
