// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Client.SS220.Experience.UiElements;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExperienceRedactorWindow : FancyWindow
{
}
