// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Numerics;
using Content.Client.SS220.Experience.UiElements;
using Content.Client.UserInterface.Controls;
using Content.Shared.Mind;
using Content.Shared.Roles;
using Content.Shared.SS220.Experience;
using Microsoft.CodeAnalysis;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExperienceRedactorWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ExperienceRedactorSystem _experienceRedactor = default!;
    private readonly ExperienceInfoSystem _experienceInfo = default!;

    private readonly LocId _noJobName = "experience-redactor-no-job-name";
    private readonly LocId _noAntagRoleName = "experience-redactor-no-antag-name";

    public ExperienceRedactorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _experienceRedactor = _entityManager.System<ExperienceRedactorSystem>();
        _experienceInfo = _entityManager.System<ExperienceInfoSystem>();

        var metadataQuery = _entityManager.GetEntityQuery<MetaDataComponent>();
        var experienceEntities = _entityManager.EntityQueryEnumerator<ExperienceComponent>();
        while (experienceEntities.MoveNext(out var uid, out var _))
        {
            ExperienceEntityOption.AddItem(metadataQuery.TryComp(uid, out var metaDataComponent) ? metaDataComponent.EntityName : uid.ToString(), uid.Id);
        }

        ExperienceEntityOption.OnItemSelected += (args) =>
        {
            SelectEntity(args.Id);
        };

        foreach (var (key, proto) in _experienceRedactor.CachedIndexedKnowledge)
        {
            KnowledgeOption.AddItem(FormattedMessage.RemoveMarkupPermissive(Loc.GetString(proto.KnowledgeName)), key);
        }

        SubmitButton.OnPressed += (_) =>
        {
            _experienceRedactor.SendChange(new EntityUid(ExperienceEntityOption.SelectedId), GetChangedData());
        };

        KnowledgeOption.OnItemSelected += OnKnowledgeOptionSelected;

        SelectEntity(ExperienceEntityOption.SelectedId);
    }

    public void SelectEntity(int uid)
    {
        SelectEntity(new EntityUid(uid));
    }

    public void SelectEntity(EntityUid uid)
    {
        // TODO: this kinda should be somehow managed and not just return
        if (!_entityManager.TryGetComponent<ExperienceComponent>(uid, out var experience))
            return;

        // TODO: handling like ask to reload or smth
        if (!ExperienceEntityOption.TrySelectId(uid.Id))
            return;

        Entity<ExperienceComponent> experienceEntity = (uid, experience);

        var data = _experienceInfo.GetEntityExperienceData(uid);

        PopulateCharacterInfo(uid);
        PopulateExperienceVerification(experienceEntity);

        UpdateKnowledge(data);
        UpdateSkill(data);
    }

    public ExperienceData GetChangedData()
    {
        var data = new ExperienceData();

        foreach (var control in KnowledgeRedactor.Children)
        {
            if (control is not KnowledgeLabel knowledgeLabel)
                continue;

            data.Knowledges.Add(knowledgeLabel.KnowledgeProto);
        }

        foreach (var control in SkillRedactor.Children)
        {
            if (control is not RedactableSkillTreeShower redactableSkill)
                continue;

            var (skillId, skillInfo) = redactableSkill.GetInfo();

            if (!_prototype.Resolve(skillId, out var skillTreePrototype))
                continue;

            if (!data.SkillDictionary.TryGetValue(skillTreePrototype.SkillGroupId, out var definitionList))
            {
                definitionList = new();
                data.SkillDictionary.Add(skillTreePrototype.SkillGroupId, definitionList);
            }

            definitionList.Add((skillId, skillInfo, 0));
        }

        return data;
    }

    private void PopulateCharacterInfo(EntityUid uid)
    {
        CharacterName.SetMessage(_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData) ? metaData.EntityName : uid.Id.ToString());

        if (!_entityManager.System<SharedMindSystem>().TryGetMind(uid, out var mindId, out var mindComponent))
            return;

        var roles = _entityManager.System<SharedRoleSystem>().MindGetAllRoleInfo(mindId);

        var job = roles.Any(x => !x.Antagonist);
        var antag = roles.Any(x => x.Antagonist);

        var jobName = job ? roles.First(x => !x.Antagonist).Name : Loc.GetString(_noJobName);
        var antagName = antag ? roles.First(x => x.Antagonist).Name : Loc.GetString(_noAntagRoleName);

        OccupationName.SetMessage(jobName);
        AntagName.SetMessage(antagName);
    }

    private void PopulateExperienceVerification(Entity<ExperienceComponent> entity)
    {
        BypassSkillCheckStatus.SetMessage(_entityManager.HasComponent<BypassSkillCheckComponent>(entity)
                                            ? Loc.GetString("experience-view-redactor-bypass-skill")
                                            : Loc.GetString("experience-view-redactor-no-bypass-skill"));

        BypassKnowledgeStatus.SetMessage(_entityManager.HasComponent<BypassKnowledgeCheckComponent>(entity)
                                            ? Loc.GetString("experience-view-redactor-bypass-knowledge")
                                            : Loc.GetString("experience-view-redactor-no-bypass-knowledge"));

        InitMaskShower.SetMessage(Loc.GetString("experience-view-redactor-init-level", ("UpperMask", (InitGainedExperienceType)(1 << BitOperations.Log2(entity.Comp.InitMask)))));
    }

    private void UpdateKnowledge(ExperienceData data)
    {
        KnowledgeRedactor.RemoveAllChildren();

        HighDivider? divider = null;
        foreach (var knowledge in data.Knowledges.OrderBy((x) => x.Id))
        {
            divider = new();
            var knowledgeControl = new KnowledgeLabel();
            knowledgeControl.SetKnowledge(knowledge);

            knowledgeControl.CloseButton.Visible = true;
            knowledgeControl.CloseButton.OnPressed += (_) =>
            {
                KnowledgeRedactor.RemoveChild(knowledgeControl);
            };

            KnowledgeRedactor.AddChild(knowledgeControl);
            KnowledgeRedactor.AddChild(divider);
        }

        if (divider is not null)
            KnowledgeRedactor.RemoveChild(divider);
    }

    private void UpdateSkill(ExperienceData data)
    {
        SkillRedactor.RemoveAllChildren();

        HighDivider? divider = null;
        foreach (var (_, skillTrees) in data.SkillDictionary.OrderBy(x => x.Key.Id))
        {
            foreach (var skillTree in skillTrees.OrderBy(x => x.Item1.Id))
            {
                var redactableSkillTreeShower = new RedactableSkillTreeShower();
                redactableSkillTreeShower.SetSkillTreeInfo(skillTree.Item1, skillTree.Item2);

                SkillRedactor.AddChild(redactableSkillTreeShower);
            }

            divider = new()
            {
                Margin = ExperienceUiStyleDefinitions.DividerThickness,
            };
            SkillRedactor.AddChild(divider);
        }

        if (divider is not null)
            SkillRedactor.RemoveChild(divider);
    }

    private void OnKnowledgeOptionSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (!_experienceRedactor.CachedIndexedKnowledge.TryGetValue(args.Id, out var knowledge))
            return;

        var divider = new HighDivider();
        var knowledgeControl = new KnowledgeLabel();
        knowledgeControl.SetKnowledge(knowledge.ID);

        knowledgeControl.CloseButton.Visible = true;
        knowledgeControl.CloseButton.OnPressed += (_) =>
        {
            KnowledgeRedactor.RemoveChild(knowledgeControl);
        };

        KnowledgeRedactor.AddChild(divider);
        KnowledgeRedactor.AddChild(knowledgeControl);
    }
}
