// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.SuperMatterCrystalUIs;

// For optimization make cache value in ServerSystem and then subscribe from client if it needs it;
[GenerateTypedNameReferences]
public sealed partial class SuperMatterObserverMenu : FancyWindow
{
    private int counter = 0;
    public SuperMatterObserverMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        PlotValueOverTime.SetXLabel("t, с");
        PlotValueOverTime.SetYLabel("u, эрг");
    }
    public void UpdateState()
    {
     //   PlotView2D.AddPointToPlot(new Vector2(counter++, counter++));
    }
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        PlotValueOverTime.AddPointToPlot(new Vector2(counter++, counter++));
    }
}
