using Content.Shared.SS220.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TtsProviderVoiceSelectorWindow : DefaultWindow
{
    private readonly TtsSystem _tts;

    public const float BetweenCategoriesMargin = 30f;

    public event Action<TtsVoicePrototype>? OnVoiceSelected;

    public readonly TtsProvider Provider;

    public TtsVoiceRequirementCheckData? RequirementsCheckData
    {
        get => _requirementsCheckData;
        set
        {
            _requirementsCheckData = value;
            foreach (var child in ContentContainer.Children)
            {
                if (child is not TtsVoiceSelectorCategoryEntry entry)
                    continue;

                entry.RequirementsCheckData = value;
            }
        }
    }
    private TtsVoiceRequirementCheckData? _requirementsCheckData;

    public TtsProviderVoiceSelectorWindow(TtsProvider provider, TtsVoiceRequirementCheckData? checkData = null)
    {
        RobustXamlLoader.Load(this);

        _tts = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<TtsSystem>();

        Provider = provider;
        _requirementsCheckData = checkData;

        Title = Loc.GetString("ui-tts-provider-voice-selector-window-title", ("providerName", Provider.ToString()));

        Refresh();
    }

    public void Refresh()
    {
        ContentContainer.RemoveAllChildren();

        var first = true;
        foreach (var (category, voices) in _tts.EnumerateProviderVoiceCategories(Provider))
        {
            var entry = new TtsVoiceSelectorCategoryEntry(category, voices)
            {
                RequirementsCheckData = _requirementsCheckData
            };
            entry.OnVoiceSelected += voice => OnVoiceSelected?.Invoke(voice);

            if (first)
                first = false;
            else
                entry.Margin = new Thickness(0, BetweenCategoriesMargin, 0, 0);

            ContentContainer.AddChild(entry);
        }
    }
}
