using Content.Shared.SS220.TTS;
using Content.Shared.SS220.TTS.Prototypes;
using Content.Shared.SS220.TTS.Requirements;
using Content.Shared.SS220.TTS.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TtsProviderVoiceSelectorWindow : DefaultWindow
{
    private readonly TtsSystem _tts;

    public const float BetweenCategoriesMargin = 30f;

    public event Action<TtsVoicePrototype>? OnVoiceSelected;

    public readonly TtsProvider Provider;

    public TtsVoiceRequirementCheckData? RequirementsCheckData
    {
        get => _requirementsCheckData;
        set
        {
            if (_requirementsCheckData == value)
                return;

            _requirementsCheckData = value;
            foreach (var child in CategoryEntriesContainer.Children)
            {
                if (child is not TtsVoiceSelectorCategoryEntry entry)
                    continue;

                entry.RequirementsCheckData = value;
            }
        }
    }
    private TtsVoiceRequirementCheckData? _requirementsCheckData;

    public TtsProviderVoiceSelectorWindow(TtsProvider provider, TtsVoiceRequirementCheckData? checkData = null)
    {
        RobustXamlLoader.Load(this);

        _tts = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<TtsSystem>();

        Provider = provider;
        _requirementsCheckData = checkData;

        Title = Loc.GetString("ui-tts-provider-voice-selector-window-title", ("providerName", Provider.ToString()));
        SearchLineEdit.OnTextChanged += _ => RefreshSearchState();

        Refresh();
    }

    public void Refresh()
    {
        CategoryEntriesContainer.RemoveAllChildren();

        var sortedCategories = _tts.EnumerateProviderVoiceCategories(Provider)
            .OrderByDescending(x => x.Key.SortPriority)
            .ThenBy(x => x.Key.LocalizedName);

        var first = true;
        foreach (var (category, voices) in sortedCategories)
        {
            var entry = new TtsVoiceSelectorCategoryEntry(category, voices)
            {
                RequirementsCheckData = _requirementsCheckData
            };
            entry.OnVoiceSelected += voice => OnVoiceSelected?.Invoke(voice);

            if (first)
                first = false;
            else
                entry.Margin = new Thickness(0, BetweenCategoriesMargin, 0, 0);

            CategoryEntriesContainer.AddChild(entry);
        }

        RefreshSearchState();
    }

    private void RefreshSearchState()
    {
        var searchText = SearchLineEdit.Text;

        foreach (var child in CategoryEntriesContainer.Children)
        {
            if (child is not TtsVoiceSelectorCategoryEntry categoryEntry)
                continue;

            var categoryPassSearch = string.IsNullOrEmpty(searchText) || categoryEntry.CategoryNameLabel.Text?.Contains(searchText) == true;

            var anyCategoryVoiceVisible = false;
            foreach (var categoryChild in categoryEntry.VoiceEntriesContainer.Children)
            {
                if (categoryChild is not TtsVoiceSelectorEntry voiceEntry)
                    continue;

                var voicePassSearch = categoryPassSearch ||
                    string.IsNullOrEmpty(searchText) ||
                    voiceEntry.Voice.ID.Contains(searchText) ||
                    voiceEntry.NameLabel.Text?.Contains(searchText) == true;

                voiceEntry.Visible = voicePassSearch;

                if (voicePassSearch)
                    anyCategoryVoiceVisible = true;
            }

            categoryEntry.Visible = anyCategoryVoiceVisible || categoryPassSearch;
        }
    }
}
