using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TtsVoiceSelectorCategoryEntry : BoxContainer
{
    private readonly TtsSystem _tts;

    public event Action<TtsVoicePrototype>? OnVoiceSelected;

    public TtsVoiceCategoryPrototype Category { get; private set; }

    private readonly List<TtsVoicePrototype> _voices = [];

    public TtsVoiceRequirementCheckData? RequirementsCheckData
    {
        get => _requirementsCheckData;
        set
        {
            if (_requirementsCheckData ==  value)
                return;

            _requirementsCheckData = value;
            RefreshLockedState();
        }
    }
    private TtsVoiceRequirementCheckData? _requirementsCheckData;

    private static readonly Thickness DividerMargin = new(0, 3f);

    private readonly Tooltip _descriptionTooltip = new();

    public TtsVoiceSelectorCategoryEntry(TtsVoiceCategoryPrototype category, IEnumerable<TtsVoicePrototype> voices)
    {
        RobustXamlLoader.Load(this);

        _tts = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<TtsSystem>();

        Category = category;
        InternalSetVoices(voices);

        Refresh();
    }

    public void Refresh()
    {
        var nameMsg = new FormattedMessage();
        nameMsg.PushColor(Category.Color);
        nameMsg.AddMessage(FormattedMessage.FromMarkupPermissive(Category.LocalizedName));
        CategoryNameLabel.SetMessage(nameMsg);

        var descriprionMsg = FormattedMessage.FromMarkupPermissive(Category.LocalizedDescription);
        if (!descriprionMsg.IsEmpty)
        {
            _descriptionTooltip.SetMessage(descriprionMsg);
            CategoryNameLabel.TooltipSupplier = _ => _descriptionTooltip;
        }
        else
            CategoryNameLabel.TooltipSupplier = null;

        Divider.Color = Category.Color;

        VoiceEntriesContainer.RemoveAllChildren();

        foreach (var voice in _voices)
        {
            var entry = new TtsVoiceSelectorEntry(voice);
            entry.OnVoiceSelected += voice => OnVoiceSelected?.Invoke(voice);

            VoiceEntriesContainer.AddChild(entry);

            var divider = new HLine()
            {
                Thickness = 2f,
                Color = Category.Color,
                Margin = DividerMargin
            };

            VoiceEntriesContainer.AddChild(divider);

            RefreshLockedState(entry);
        }
    }

    public void SetData(TtsVoiceCategoryPrototype category, IEnumerable<TtsVoicePrototype> voices)
    {
        Category = category;
        InternalSetVoices(voices);

        Refresh();
    }

    private void RefreshLockedState()
    {
        foreach (var control in VoiceEntriesContainer.Children)
        {
            if (control is not TtsVoiceSelectorEntry entry)
                continue;

            RefreshLockedState(entry);
        }
    }

    private void RefreshLockedState(TtsVoiceSelectorEntry entry)
    {
        if (RequirementsCheckData is { } checkData && !_tts.IsPassVoiceRequirements(entry.Voice, checkData, out var reason))
            entry.Lock(reason);
        else
            entry.Unlock();
    }

    private void InternalSetVoices(IEnumerable<TtsVoicePrototype> voices)
    {
        _voices.Clear();
        _voices.AddRange(voices.OrderBy(x => x.LocalizedName));
    }
}
