using Content.Shared.SS220.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TTSVoicePreferencesTabEntry : PanelContainer
{
    [Dependency] private IEntityManager _entity = default!;

    private readonly TTSSystem _tTSSystem = default!;

    public readonly TTSProvider Provider;
    public readonly ProtoId<TTSVoicePrototype> ProtoId;

    public TTSVoicePreferencesTabEntry(TTSProvider provider, ProtoId<TTSVoicePrototype> protoId)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _tTSSystem = _entity.System<TTSSystem>();

        Provider = provider;
        ProtoId = protoId;

        Refresh();

        VoicePlayButton.OnPressed += _ => _tTSSystem.RequestTTSVoiceTest(protoId);
    }

    public void Refresh()
    {
        ProviderNameLabel.Text = Provider.ToString();
        VoicePrototypeIdLabel.Text = ProtoId;
    }

    public TTSVoicePreferencesTabEntry Clone()
    {
        return new TTSVoicePreferencesTabEntry(Provider, ProtoId);
    }
}
