using Content.Shared.SS220.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TtsVoiceSelectorCategoryEntry : BoxContainer
{
    [Dependency] private IResourceCache _cache = default!;

    public event Action<TtsVoicePrototype>? OnVoiceSelected;

    public TtsVoiceCategoryPrototype Category { get; private set; }
    public IReadOnlyList<TtsVoicePrototype> Voices => _voices;
    private readonly List<TtsVoicePrototype> _voices;

    public TtsVoiceSelectorCategoryEntry(TtsVoiceCategoryPrototype category, IEnumerable<TtsVoicePrototype> voices)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Category = category;
        _voices = [.. voices];

        Refresh();
    }

    public void Refresh()
    {
        CategoryNameLabel.Text = Category.LocalizedName;
        CategoryNameLabel.FontOverride = new VectorFont(_cache.GetResource<FontResource>("/Fonts/NotoSans/NotoSans-Bold.ttf"), 14);

        VoiceEntriesContainer.RemoveAllChildren();

        foreach (var voice in _voices)
        {
            var entry = new TtsVoiceSelectorEntry(voice);
            entry.OnVoiceSelected += voice => OnVoiceSelected?.Invoke(voice);

            VoiceEntriesContainer.AddChild(entry);
        }
    }

    public void SetData(TtsVoiceCategoryPrototype category, IEnumerable<TtsVoicePrototype> voices)
    {
        Category = category;
        _voices.Clear();

        foreach (var voice in voices)
            _voices.Add(voice);

        Refresh();
    }
}
