using Content.Client.Administration.UI.CustomControls;
using Content.Client.SS220.UserInterface;
using Content.Shared.SS220.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.SS220.TTS.UI;

[GenerateTypedNameReferences]
public sealed partial class TtsVoicePreferencesTab : BoxContainer
{
    [Dependency] private IUserInterfaceManager _ui = default!;
    [Dependency] private IInputManager _input = default!;

    public event Action? OnPreferencesChanged;

    public static readonly Color CellBackgroundColor = Color.FromHex("#2F2F3B");
    public const float ProviderColumnWidth = 250f;

    public TtsVoicePreferences VoicePreferences { get; private set; }

    private int? _draggedEntryStartPos;
    private TtsVoicePreferencesTabEntry? _draggingEntry;

    private TtsProviderVoiceSelectorWindow? _selectorWindow;
    private TtsVoicePreferencesTabEntry? _editingEntry;

    private Dictionary<TtsProvider, TtsVoicePreferencesTabEntry> _entriesDict = new();

    public TtsVoiceRequirementCheckData? RequirementsCheckData
    {
        get => _requirementsCheckData;
        set
        {
            _requirementsCheckData = value;
            _selectorWindow?.RequirementsCheckData = value;
        }
    }
    private TtsVoiceRequirementCheckData? _requirementsCheckData;

    public TtsVoicePreferencesTab() : this(null) { }

    public TtsVoicePreferencesTab(TtsVoicePreferences? preferences = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ProviderHeaderBackground.PanelOverride = new StyleBoxFlat()
        {
            BackgroundColor = CellBackgroundColor
        };
        ProviderHeaderLabel.SetWidth = ProviderColumnWidth;

        preferences ??= [];

        // fill not setted providers
        preferences.SoftMergeWith(SharedTtsSystem.DefaultVoicePreferences);

        VoicePreferences = preferences;

        OnKeyBindUp += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            StopDragEntry();
        };

        Refresh();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_draggingEntry != null)
        {
            const int swapStep = 2; // entry + HSeprator
            const float swapThreshold = 5f;

            var entryBox = _draggingEntry.SizeBox;
            var entryMousePos = _ui.MousePositionScaled.Position - _draggingEntry.GlobalPosition;

            var indexDelta = 0;
            if (entryMousePos.Y < entryBox.Top - swapThreshold)
                indexDelta = -swapStep;
            else if (entryMousePos.Y > entryBox.Bottom + swapThreshold)
                indexDelta = swapStep;

            if (indexDelta == 0)
                return;

            var oldIndex = _draggingEntry.GetPositionInParent();
            var newIndex = Math.Clamp(oldIndex + indexDelta, 0, EntriesContainer.ChildCount - 1);

            if (newIndex == oldIndex)
                return;

            var childOnNewIndex = EntriesContainer.GetChild(newIndex);

            _draggingEntry.SetPositionInParent(newIndex);
            childOnNewIndex.SetPositionInParent(oldIndex);

            EntriesContainer.InvalidateMeasure();
        }
    }

    protected override void MouseExited()
    {
        base.MouseExited();

        var hoveredControl = _ui.MouseGetControl(_input.MouseScreenPosition);
        if (hoveredControl != null && hoveredControl.IsChildOf(this, recurcive: true))
            return;

        StopDragEntry();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        CloseSelecotorWindow();
    }

    public void Refresh()
    {
        EntriesContainer.RemoveAllChildren();
        _entriesDict.Clear();

        var first = true;
        foreach (var (provider, protoId) in VoicePreferences)
        {
            if (first)
                first = false;
            else
                EntriesContainer.AddChild(new HSeparator());

            var entry = new TtsVoicePreferencesTabEntry(provider, protoId);
            entry.OnKeyBindDown += args =>
            {
                if (args.Function != EngineKeyFunctions.UIClick)
                    return;

                StartDragEntry(entry);
            };

            entry.VoiceSelectorButton.OnPressed += _ => OpenSelectorWindow(provider);
            entry.OnExitedTree += () =>
            {
                if (entry != _editingEntry)
                    return;

                CloseSelecotorWindow();
            };


            EntriesContainer.AddChild(entry);
            _entriesDict.Add(provider, entry);
        }
    }

    public void SetPreferences(TtsVoicePreferences pref)
    {
        VoicePreferences = pref;
        Refresh();

        OnPreferencesChanged?.Invoke();
    }

    private void OpenSelectorWindow(TtsProvider provider)
    {
        if (_selectorWindow != null)
            CloseSelecotorWindow();

        if (!_entriesDict.TryGetValue(provider, out var entry))
            return;

        entry.VoiceSelectorButton.Pressed = true;

        var window = new TtsProviderVoiceSelectorWindow(provider, _requirementsCheckData);
        window.OnClose += CloseSelecotorWindow;
        window.OnVoiceSelected += voice =>
        {
            VoicePreferences[provider] = voice;
            CloseSelecotorWindow();
            Refresh();

            OnPreferencesChanged?.Invoke();
        };

        window.OpenCentered();
        _selectorWindow = window;
        _editingEntry = entry;
    }

    private void CloseSelecotorWindow()
    {
        if (_selectorWindow == null)
            return;

        _selectorWindow.Close();
        _selectorWindow = null;

        _editingEntry?.VoiceSelectorButton.Pressed = false;
        _editingEntry = null;
    }

    private void StartDragEntry(TtsVoicePreferencesTabEntry entry)
    {
        StopDragEntry();

        DebugTools.Assert(_draggingEntry == null);

        _draggingEntry = entry;
        _draggingEntry.LightOverlay.Visible = true;

        _draggedEntryStartPos = _draggingEntry.GetPositionInParent();
    }

    private void StopDragEntry()
    {
        if (_draggingEntry == null)
            return;

        _draggingEntry.LightOverlay.Visible = false;

        var newPos = _draggingEntry.GetPositionInParent();
        if (newPos != _draggedEntryStartPos)
        {
            VoicePreferences.Remove(_draggingEntry.Provider);
            VoicePreferences.Insert(newPos, _draggingEntry.Provider, _draggingEntry.ProtoId);
            Refresh();

            OnPreferencesChanged?.Invoke();
        }

        _draggingEntry = null;
        _draggedEntryStartPos = null;
    }
}
