// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Zones.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class ZoneColorSelectorPopup : Popup
{
    public Action<Color>? OnColorSelected;

    public ZoneColorSelectorPopup()
    {
        RobustXamlLoader.Load(this);
        AcceptButton.OnPressed += _ =>
        {
            OnColorSelected?.Invoke(ColorSelector.Color);
        };

        UserInterfaceManager.ModalRoot.AddChild(this);
    }

    public ZoneColorSelectorPopup(Color color)
    {
        ColorSelector.Color = color;
    }

    public void SetColor(Color color)
    {
        ColorSelector.Color = color;
    }
}
