// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Zones.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class ZoneWarningWindow : DefaultWindow
{
    public ZoneWarningWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
