using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Trigger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Trigger.UI;

[GenerateTypedNameReferences]
public sealed partial class RattleWindow : FancyWindow
{
    public event Action<string, bool>? OnChannelToggled;

    public event Action<bool>? OnAllChannelToggled;

    private bool _toggleState = true;

    public RattleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleAllChannels.OnPressed += _ =>
        {
            OnAllChannelToggled?.Invoke(_toggleState);
        };
    }

    public void SetChannels(List<RattleChannelEntry> channels)
    {
        ChannelsList.DisposeAllChildren();

        var allOn = true;

        foreach (var channel in channels)
        {
            if (!channel.Enabled)
                allOn = false;

            var checkbox = new CheckBox
            {
                Text = channel.Name,
                Pressed = channel.Enabled,
            };

            checkbox.Label.Modulate = channel.Color;

            checkbox.OnToggled += args =>
            {
                OnChannelToggled?.Invoke(channel.Key, args.Pressed);
            };

            ChannelsList.AddChild(checkbox);
        }

        _toggleState = !allOn;
        ToggleAllChannels.Text = Loc.GetString("headset-ui-toggle-all-channels", ("value", _toggleState));
    }
}
