using Content.Client.SS220.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Client.Verbs.UI;
using Content.Shared.SS220.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Network;

namespace Content.Client.SS220.Administration.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class CustomObjectivesListControl : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!;

    private readonly CustomObjectivesSystem _customObjectivesSystem;

    private readonly Dictionary<NetUserId, CustomObjectivesPlayerInfo> _playersBySession = new();
    private NetUserId? _selectedPlayerSessionId;

    public event Action<CustomObjectivesPlayerInfo?>? OnSelectionChanged;

    public Func<CustomObjectivesPlayerInfo, string, string>? OverrideText;

    public CustomObjectivesListControl()
    {
        IoCManager.InjectDependencies(this);
        _customObjectivesSystem = _entManager.System<CustomObjectivesSystem>();
        RobustXamlLoader.Load(this);
        CustomObjectivesListContainer.ItemPressed += CustomObjectivesListItemPressed;
        CustomObjectivesListContainer.GenerateItem += GenerateButton;

        BackgroundPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = AdminListControlHelper.ListBackgroundColor };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _customObjectivesSystem.CustomObjectivesListChanged += UpdatePlayerList;
        UpdatePlayerList(_customObjectivesSystem.Players);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _customObjectivesSystem.CustomObjectivesListChanged -= UpdatePlayerList;
    }

    public void UpdatePlayerList(IReadOnlyList<CustomObjectivesPlayerInfo> players)
    {
        _playersBySession.Clear();
        var listData = new List<ListData>(players.Count);

        foreach (var player in players)
        {
            _playersBySession[player.SessionId] = player;
            listData.Add(new CustomObjectivesListData(player));
        }

        CustomObjectivesListContainer.PopulateList(listData);

        if (_selectedPlayerSessionId is not { } selectedPlayerSessionId)
            return;

        if (_playersBySession.TryGetValue(selectedPlayerSessionId, out var selectedPlayer))
        {
            OnSelectionChanged?.Invoke(selectedPlayer);
            return;
        }

        _selectedPlayerSessionId = null;
        OnSelectionChanged?.Invoke(null);
    }

    private void CustomObjectivesListItemPressed(BaseButton.ButtonEventArgs? args, ListData? data)
    {
        if (args is null)
            return;

        if (data is not CustomObjectivesListData { Info: var selectedPlayer })
            return;

        if (args.Event.Function == EngineKeyFunctions.UIClick)
        {
            _selectedPlayerSessionId = selectedPlayer.SessionId;
            OnSelectionChanged?.Invoke(selectedPlayer);

            if (OverrideText != null)
                AdminListControlHelper.UpdateButtonLabel(args.Button, GetText(selectedPlayer));
        }
        else if (args.Event.Function == EngineKeyFunctions.UseSecondary && selectedPlayer.NetEntity != null)
        {
            _userInterfaceManager.GetUIController<VerbMenuUIController>().OpenVerbMenu(_entManager.GetEntity(selectedPlayer.NetEntity.Value));
        }
    }

    private string GetText(CustomObjectivesPlayerInfo info)
    {
        var text = Loc.GetString(
            "admin-custom-objectives-entry",
            ("character", info.CharacterName),
            ("username", info.Username),
            ("count", info.ObjectiveCount));

        if (OverrideText != null)
            text = OverrideText.Invoke(info, text);

        return text;
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not CustomObjectivesListData { Info: var info })
            return;

        button.AddChild(new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Children =
            {
                new Label
                {
                    ClipText = true,
                    Text = GetText(info)
                }
            }
        });
        button.EnableAllKeybinds = true;
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);
    }
}

public record CustomObjectivesListData(CustomObjectivesPlayerInfo Info) : ListData;
