using System.Linq;
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Controls;
using Content.Client.Verbs.UI;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client.SS220.Administration.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class GameRulesListControl : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!;

    private readonly AdminSystem _adminSystem;

    private List<GameRuleInfo> _gameRulesList = new();

    public event Action<GameRuleInfo?>? OnSelectionChanged;

    public Func<GameRuleInfo, string, string>? OverrideText;
    public GameRulesListControl()
    {
        IoCManager.InjectDependencies(this);
        _adminSystem = _entityManager.System<AdminSystem>();

        RobustXamlLoader.Load(this);
        GameRulesListContainer.ItemPressed += GameRulesListItemPressed;
        GameRulesListContainer.GenerateItem += GenerateButton;
        BackgroundPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(32, 32, 40) };
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _adminSystem.GameRulesListChanged += PopulateList;
        PopulateList(_adminSystem.GameRulesList);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _adminSystem.GameRulesListChanged -= PopulateList;
    }

    private void GameRulesListItemPressed(BaseButton.ButtonEventArgs? args, ListData? data)
    {
        if (args is null)
            return;

        if (data is not GameRuleListData { Info: var selectedGameRule })
            return;
        if (args.Event.Function == EngineKeyFunctions.UIClick)
        {
            OnSelectionChanged?.Invoke(selectedGameRule);

            if (OverrideText != null && args.Button.Children.FirstOrDefault()?.Children?.FirstOrDefault() is Label label)
                label.Text = GetText(selectedGameRule);
        }
        else if (args.Event.Function == EngineKeyFunctions.UseSecondary && selectedGameRule.Entity != null)
        {
            var entity = _entityManager.GetEntity(selectedGameRule.Entity.Value);
            if (_entityManager.EntityExists(entity))
                _userInterfaceManager.GetUIController<VerbMenuUIController>().OpenVerbMenu(entity);
        }
    }

    private void PopulateList(IReadOnlyList<GameRuleInfo>? gameRules = null)
    {
        gameRules ??= _adminSystem.GameRulesList;

        _gameRulesList = gameRules.ToList();

        if (_gameRulesList is not null)
            GameRulesListContainer.PopulateList(_gameRulesList.Select(info => new GameRuleListData(info)).ToList());
    }

    private string GetText(GameRuleInfo info)
    {
        var text = $"n{info.Entity} - {info.Name}";
        if (OverrideText != null)
            text = OverrideText.Invoke(info, text);
        return text;
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not GameRuleListData { Info: var info })
            return;

        button.AddChild(new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            Children =
            {
                new Label
                {
                    ClipText = true,
                    Text = GetText(info)
                }
            }
        });
        button.EnableAllKeybinds = true;
        button.AddStyleClass(ListContainer.StyleClassListContainerButton);
    }
}

public record GameRuleListData(GameRuleInfo Info) : ListData;

