using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.SetSelector;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SetSelector;

[GenerateTypedNameReferences]
public sealed partial class SetSelectorMenu : FancyWindow
{
    [Dependency] private IEntitySystemManager _sysMan = default!;
    private SpriteSystem _spriteSystem;

    public event Action? OnApprove;
    public event Action<int>? OnSetChange;

    public SetSelectorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        ApproveButton.OnPressed += args =>
        {
            OnApprove?.Invoke();
        };
    }

    public void UpdateState(SetSelectorBoundUserInterfaceState state)
    {
        SetsGrid.RemoveAllChildren();
        var selectedNumber = 0;
        foreach (var (set, info) in state.Sets)
        {
            var child = new SelectableSet(info, _spriteSystem);

            child.SetButton.OnButtonDown += (args) =>
            {
                OnSetChange?.Invoke(set);
            };

            SetsGrid.AddChild(child);

            if (info.Selected)
                selectedNumber++;
        }

        Title = Loc.GetString(state.ToolName);
        Description.Text = Loc.GetString(state.ToolDesc, ("maxCount", state.MaxSelectedSets));
        SelectedSets.Text = Loc.GetString("set-selector-window-selected", ("selectedCount", selectedNumber), ("maxCount", state.MaxSelectedSets));
        ApproveButton.Disabled = selectedNumber != state.MaxSelectedSets;
    }
}
