"Изменения: спрайты":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

"Изменения: Карты":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

"Изменения: Интерфейсы":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

"Изменения: Локализация":
- changed-files:
  - any-glob-to-any-file: 'Resources/Locale/**/*.ftl'

"Изменения: Шейдеры":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

"Изменения: Прототипы":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files:
    - "Resources/Prototypes/**/*.yml"
    - '!Resources/Prototypes/Maps/**/*.yml'
