- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxBox
#  - CorvaxIshimura
  - CorvaxAvrite
  - Bagel
  - Cluster
  - Kettle
  - Marathon
  - Omega
  - Origin
  - Meta
  - Barratry
  - Aspid
  - Fland  
