- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxBox
  - CorvaxIshimura
  - CorvaxAvrite
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster
  - Core
  - Fland
  - Kettle
  - Marathon
<<<<<<< HEAD
  - Omega
  - Origin
=======
>>>>>>> syndie/master
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
