using Content.Client.SS220.Zones.Systems;
using Content.Shared.SS220.Zones.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZoneEntry : ContainerButton
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public Entity<ZoneComponent> ZoneEntity;

    public ZoneEntry(Entity<ZoneComponent> entity)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ZoneEntity = entity;

        AddStyleClass(StyleClassButton);

        Refresh();
    }

    public void Refresh()
    {
        IDLabel.Text = _entityManager.GetNetEntity(ZoneEntity).ToString();
        NameLabel.Text = ZoneEntity.Comp.ZoneParams?.Name ?? "Unknown";
    }

    public string GetFilteringString()
    {
        return $"{IDLabel.Text} {NameLabel.Text}";
    }
}
