
using Content.Shared.SS220.Zones.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.SS220.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZoneDataEntry : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public Entity<ZonesDataComponent> ZonesData;

    public Dictionary<EntityUid, ZoneEntry> ZoneEntries = new();

    private bool _collapsed;

    public ZoneDataEntry(Entity<ZonesDataComponent> entity)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ZonesData = entity;

        CollapseButtonTexture.AddStyleClass(OptionButton.StyleClassOptionTriangle);
        ParentButton.AddStyleClass(ContainerButton.StyleClassButton);
        CollapseButton.OnPressed += _ => ToggleCollapse();
        ParentBackgroundPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = new Color(60, 60, 60) };
        Refresh();
    }

    public void Refresh()
    {
        ParentIDLabel.Text = ZonesData.Owner.ToString();

        var name = "Unknown";
        if (_entityManager.TryGetComponent<MetaDataComponent>(ZonesData, out var meta) &&
            !string.IsNullOrEmpty(meta.EntityName) && !string.IsNullOrWhiteSpace(meta.EntityName))
            name = meta.EntityName;

        ParentNameLabel.Text = name;

        var toDelete = ZoneEntries.ToDictionary();
        var toAdd = new Dictionary<EntityUid, ZoneEntry>();

        foreach (var netEnt in ZonesData.Comp.Zones)
        {
            if (!_entityManager.TryGetEntity(netEnt, out var entity) ||
                !_entityManager.TryGetComponent<ZoneComponent>(entity, out var zoneComp))
                continue;

            if (!toDelete.Remove(entity.Value))
                toAdd.Add(entity.Value, new ZoneEntry((entity.Value, zoneComp)));
        }

        foreach (var (key, value) in toDelete)
        {
            ZonesContainer.RemoveChild(value);
            ZoneEntries.Remove(key);
        }

        foreach (var (key, value) in toAdd)
        {
            ZonesContainer.AddChild(value);
            ZoneEntries.Add(key, value);
        }

        SortEntries();

        foreach (var value in ZoneEntries.Values)
            value.Refresh();
    }

    public void SortEntries()
    {
        var sorted = ZoneEntries.OrderBy(e => e.Key.Id).ToDictionary();
        ZonesContainer.RemoveAllChildren();
        foreach (var value in sorted.Values)
            ZonesContainer.AddChild(value);

        ZoneEntries = sorted;
    }

    public void ToggleCollapse()
    {
        _collapsed = !_collapsed;
        Collapsible.Visible = !_collapsed;
    }
}
