// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.BoxLayout;
using Content.Client.SS220.Overlays;
using Content.Client.SS220.Zones.Systems;
using Content.Client.SS220.Zones.UI.CustomControls;
using Content.Client.Stylesheets;
using Content.Shared.Prototypes;
using Content.Shared.SS220.Maths;
using Content.Shared.SS220.Zones.Components;
using Content.Shared.SS220.Zones.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Numerics;

namespace Content.Client.SS220.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZoneEditor : PanelContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IBoxLayoutManager _boxLayoutManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ZonesSystem _zones = default!;

    private readonly ZoneEditorBoxesOverlayProvider _overlayProvider;

    private readonly ZonePrototypeSelectorPopup _prototypeSelectorPopup = new();
    private readonly ZoneColorSelectorPopup _colorSelectorPopup = new();

    public static Vector2 DefaultMinSize => new(500f, 270f);

    private static Color SizeOptionsBackgroundColor => new(32, 32, 32);
    private static Color SizeOptionsBorderColor => new(128, 128, 128);
    private static Thickness SizeOptionsBorderThickness => new(2);

    public event Action<ZoneArgs>? OnApply;
    public event Action<ZoneArgs>? OnCancel;

    public ZoneArgs? ChangedArgs
    {
        get => _changedArgs;
        set
        {
            _changedArgs = value;
            CancelLayout();
            Refresh();
        }
    }
    private ZoneArgs? _changedArgs = default!;

    public ZoneArgs OriginalArgs { get; private set; } = default!;

    public ZoneArgs ShowedArgs => ChangedArgs ?? OriginalArgs;

    public ZoneEditorSetting EditorSetting { get; private set; } = ZoneEditorSetting.ReadWrite;

    private BoxLayoutMode _layoutMode = BoxLayoutMode.Adding;

    public ZoneEditor() : this(null) { }

    public ZoneEditor(Entity<ZoneComponent> ent, ZoneEditorSetting setting = ZoneEditorSetting.ReadWrite) : this(GetZoneArgs(ent), setting) { }

    public ZoneEditor(ZoneArgs? args, ZoneEditorSetting setting = ZoneEditorSetting.ReadWrite)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        MinSize = DefaultMinSize;

        var overlay = BoxesOverlay.GetOverlay();
        _overlayProvider = overlay.EnsureProvider<ZoneEditorBoxesOverlayProvider>();
        _overlayProvider.Panel = this;

        _zones = _entityManager.System<ZonesSystem>();

        SizeOptionsBackground.PanelOverride = new StyleBoxFlat()
        {
            BackgroundColor = SizeOptionsBackgroundColor,
            BorderColor = SizeOptionsBorderColor,
            BorderThickness = SizeOptionsBorderThickness
        };

        PrototypeSelectorButton.AddStyleClass(StyleNano.StyleClassChatFilterOptionButton);
        ColorSelectorButton.AddStyleClass(StyleNano.StyleClassChatFilterOptionButton);

        ApplyButton.OnPressed += _ => OnApply?.Invoke(ShowedArgs);
        CancelButton.OnPressed += _ => OnCancel?.Invoke(ShowedArgs);

        InitInput();
        InitTooltips();

        SetEditorSetting(setting, refresh: false);
        SetOriginalArgs(args, refresh: false);
        Refresh();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _colorSelectorPopup.Close();
        RemoveLayoutReact();
        SetOverlay(false);
    }

    public void Refresh()
    {
        _prototypeSelectorPopup.Close();
        _colorSelectorPopup.Close();

        CancelLayout();

        var showedArgs = ShowedArgs;

        NameLineEdit.Text = showedArgs.Name;
        PrototypeIDLineEdit.Text = showedArgs.ProtoId;
        HexColorLineEdit.Text = showedArgs.Color.ToHex();
        ParentNetIDLineEdit.Text = _entityManager.GetNetEntity(showedArgs.Parent).ToString();

        Box2ListContainer.RemoveAllChildren();
        for (var i = 0; i < showedArgs.Area.Count; i++)
        {
            var box = showedArgs.Area[i];
            var entry = new ZoneBoxEntry(box);
            var index = i;
            entry.OnBoxChanged += newBox =>
            {
                var newArea = showedArgs.Area.ToList();
                newArea[index] = newBox;
                ChangeArea(newArea);
            };
            Box2ListContainer.AddChild(entry);
        }

        RefreshEditable();
        _overlayProvider.Refresh();
    }

    public void ClearChanges()
    {
        ChangedArgs = null;
    }

    public void SetOriginalArgs(Entity<ZoneComponent> ent, bool refresh = true)
    {
        SetOriginalArgs(GetZoneArgs(ent, _entityManager), refresh);
    }

    public void SetOriginalArgs(ZoneArgs? args, bool refresh = true)
    {
        OriginalArgs = args ?? new ZoneArgs();

        if (refresh)
            Refresh();
    }

    public void SetOverlay(bool active)
    {
        _overlayProvider.Active = active;
    }

    public void SetEditorSetting(ZoneEditorSetting setting, bool refresh = true)
    {
        EditorSetting = setting;

        if (refresh)
            Refresh();
    }

    private void InitInput()
    {
        AddBoxButton.OnToggled += e =>
        {
            if (e.Pressed)
                StartLayout(BoxLayoutMode.Adding);
            else
                CancelLayout();
        };
        CutBoxButton.OnToggled += e =>
        {
            if (e.Pressed)
                StartLayout(BoxLayoutMode.Cutting);
            else
                CancelLayout();
        };

        AttachToGridButton.OnToggled += e =>
        {
            if (_boxLayoutManager.Active)
                _boxLayoutManager.AttachToGrid = e.Pressed;
        };

        ParentNetIDLineEdit.OnFocusExit += args =>
        {
            if (NetEntity.TryParse(args.Text, out var netParent) && _entityManager.TryGetEntity(netParent, out var parent))
                ChangeParent(parent.Value);
            else
                Refresh();
        };
        ParentNetIDLineEdit.OnTextEntered += args =>
        {
            if (NetEntity.TryParse(args.Text, out var netParent) && _entityManager.TryGetEntity(netParent, out var parent))
                ChangeParent(parent.Value);
            else
                Refresh();
        };

        NameLineEdit.OnFocusExit += args => ChangeName(args.Text);
        NameLineEdit.OnTextEntered += args => ChangeName(args.Text);

        PrototypeIDLineEdit.OnFocusExit += args => ChangeProtoID(args.Text);
        PrototypeIDLineEdit.OnTextEntered += args => ChangeProtoID(args.Text);

        HexColorLineEdit.OnFocusExit += args => ChangeColor(args.Text);
        HexColorLineEdit.OnTextEntered += args => ChangeColor(args.Text);

        PrototypeSelectorButton.OnPressed += _ =>
        {
            _prototypeSelectorPopup.Refresh();

            var globalPos = ColorSelectorButton.GlobalPosition;
            var box = UIBox2.FromDimensions(globalPos, _prototypeSelectorPopup.MinSize);
            _prototypeSelectorPopup.Open(box);
        };

        _prototypeSelectorPopup.OnPrototypeSelected += proto => ChangeProtoID(proto.ID);
        _prototypeSelectorPopup.OnVisibilityChanged += args => PrototypeSelectorButton.Pressed = args.Visible;

        ColorSelectorButton.OnPressed += _ =>
        {
            var color = ShowedArgs.Color;
            _colorSelectorPopup.SetColor(color);

            var globalPos = ColorSelectorButton.GlobalPosition;
            var box = UIBox2.FromDimensions(globalPos, _colorSelectorPopup.MinSize);
            _colorSelectorPopup.Open(box);
        };

        _colorSelectorPopup.OnColorSelected += color => ChangeColor(color);
        _colorSelectorPopup.OnVisibilityChanged += args => ColorSelectorButton.Pressed = args.Visible;
    }

    private void InitTooltips()
    {
        NameLabel.ToolTip = Loc.GetString("zone-editor-name-tooltip");
        PrototypeIDLabel.ToolTip = Loc.GetString("zone-editor-prototype-id-tooltip");
        HexColorLabel.ToolTip = Loc.GetString("zone-editor-hex-color-tooltip");
        ParentNetIDLabel.ToolTip = Loc.GetString("zone-editor-parent-net-id-tooltip");
        AttachToGridButton.ToolTip = Loc.GetString("zone-editor-attach-to-grid-button-tooltip");
    }

    private void RefreshEditable()
    {
        var editable = EditorSetting is ZoneEditorSetting.ReadWrite;

        NameLineEdit.Editable = editable;
        PrototypeIDLineEdit.Editable = editable;
        HexColorLineEdit.Editable = editable;
        ParentNetIDLineEdit.Editable = editable;

        ApplyButton.Disabled = !editable;
        CancelButton.Disabled = !editable;

        AttachToGridButton.Disabled = !editable;
        AddBoxButton.Disabled = !editable;
        CutBoxButton.Disabled = !editable;

        foreach (var child in Box2ListContainer.Children)
        {
            if (child is not ZoneBoxEntry entry)
                continue;

            entry.Editable = editable;
        }
    }

    private void AddLayotReact()
    {
        _boxLayoutManager.Ended += OnLayoutEnded;
        _boxLayoutManager.Cancelled += OnLayoutCancelled;
        _boxLayoutManager.SetOverlay(true);
    }

    private void RemoveLayoutReact()
    {
        _boxLayoutManager.Ended -= OnLayoutEnded;
        _boxLayoutManager.Cancelled -= OnLayoutCancelled;
        _boxLayoutManager.SetOverlay(false);

        AddBoxButton.Pressed = false;
        CutBoxButton.Pressed = false;
    }

    private void OnLayoutEnded(IBoxLayoutManager.BoxArgs boxArgs)
    {
        var newZoneArgs = ShowedArgs;
        if (!newZoneArgs.Parent.IsValid())
            newZoneArgs.Parent = boxArgs.Parent;
        else if (boxArgs.Parent != newZoneArgs.Parent)
        {
            CancelLayout();
            return;
        }

        var newArea = newZoneArgs.Area.ToList();
        switch (_layoutMode)
        {
            case BoxLayoutMode.Adding:
                newArea.Add(boxArgs.Box);
                break;

            case BoxLayoutMode.Cutting:
                var cutter = boxArgs.Box;
                newArea = Box2Helper.SubstructBox(newArea, cutter);
                break;
        }

        newArea = [.. newArea.Select(b =>
        {
            var left = MathF.Round(b.Left, 2);
            var bottom = MathF.Round(b.Bottom, 2);
            var right = MathF.Round(b.Right, 2);
            var top = MathF.Round(b.Top, 2);
            return new Box2(left, bottom, right, top);
        })];

        newArea = _zones.RecalculateArea(newArea, newZoneArgs.Parent);
        newZoneArgs.Area = newArea;
        ChangeArgs((ref ZoneArgs args) => args = newZoneArgs);
    }

    private void OnLayoutCancelled()
    {
        RemoveLayoutReact();
        _boxLayoutManager.SetOverlay(false);
    }

    private static ZoneArgs GetZoneArgs(Entity<ZoneComponent>? ent, IEntityManager? entityManager = null)
    {
        if (ent is null)
            return new ZoneArgs();

        entityManager ??= IoCManager.Resolve<EntityManager>();

        entityManager.TryGetComponent<TransformComponent>(ent, out var xform);
        entityManager.TryGetComponent<MetaDataComponent>(ent, out var metaData);

        return new ZoneArgs()
        {
            Parent = xform?.ParentUid ?? ent.Value,
            ProtoId = metaData?.EntityPrototype?.ID ?? SharedZonesSystem.DefaultZoneProtoId,
            Area = ent.Value.Comp.Area,
            Name = metaData?.EntityName ?? string.Empty,
            Color = ent.Value.Comp.Color,
        };
    }

    private void StartLayout(BoxLayoutMode mode)
    {
        if (_boxLayoutManager.Active)
            return;

        _layoutMode = mode;

        switch (mode)
        {
            case BoxLayoutMode.Adding:
                _boxLayoutManager.StartNew();
                _boxLayoutManager.AttachToGrid = AttachToGridButton.Pressed;
                break;

            case BoxLayoutMode.Cutting:
                _boxLayoutManager.StartNew();
                _boxLayoutManager.AttachToGrid = AttachToGridButton.Pressed;
                _boxLayoutManager.OverlayOverrideColor = Color.Red;
                break;
        }

        AddLayotReact();
        _boxLayoutManager.SetOverlay(true);
    }

    private void CancelLayout()
    {
        if (!_boxLayoutManager.Active)
            return;

        _boxLayoutManager.Cancel();
    }

    #region Params changes
    private bool ChangeParent(EntityUid parent, bool refresh = true)
    {
        return ChangeArgs((ref ZoneArgs args) => args.Parent = parent, refresh: refresh);
    }

    private bool ChangeArea(List<Box2> area, bool refresh = true)
    {
        return ChangeArgs((ref ZoneArgs args) => args.Area = area, refresh: refresh, recalculate: true);
    }

    private bool ChangeName(string name, bool refresh = true)
    {
        return ChangeArgs((ref ZoneArgs args) => args.Name = name, refresh: refresh);
    }

    private bool ChangeProtoID(EntProtoId<ZoneComponent> protoId, bool refresh = true)
    {
        if (!_prototype.TryIndex<EntityPrototype>(protoId, out var proto) ||
            !proto.HasComponent<ZoneComponent>())
            return false;

        return ChangeArgs((ref ZoneArgs args) => args.ProtoId = protoId, refresh: refresh);
    }

    private bool ChangeColor(string hex, bool refresh = true)
    {
        if (!Color.TryParse(hex, out var color))
            return false;

        return ChangeColor(color, refresh);
    }

    private bool ChangeColor(Color value, bool refresh = true)
    {
        return ChangeArgs((ref ZoneArgs args) => args.Color = value, refresh: refresh);
    }

    private bool ChangeArgs(ActionRefZoneArgs action, bool refresh = true, bool recalculate = false)
    {
        if (EditorSetting is not ZoneEditorSetting.ReadWrite)
            return false;

        var args = ShowedArgs;
        action.Invoke(ref args);

        if (recalculate)
            args.Area = _zones.RecalculateArea(args.Area, args.Parent);

        _changedArgs = args;
        if (refresh)
            Refresh();

        return true;
    }

    private delegate void ActionRefZoneArgs(ref ZoneArgs box);
    #endregion

    private enum BoxLayoutMode
    {
        Adding,
        Cutting
    }

    public enum ZoneEditorSetting
    {
        ReadOnly,
        ReadWrite
    }

    private sealed class ZoneEditorBoxesOverlayProvider() : BoxesOverlay.BoxesOverlayProvider()
    {
        public ZoneEditor? Panel;
        private (EntityUid Parent, List<Box2> Boxes)? _addedBoxes;
        private (EntityUid Parent, List<Box2> Boxes)? _deletedBoxes;

        private const float ColorAlpha = 0.5f;

        public void Refresh()
        {
            _addedBoxes = null;
            _deletedBoxes = null;

            if (Panel == null)
                return;

            var changed = Panel.ChangedArgs;
            if (changed == null)
                return;

            var original = Panel.OriginalArgs;
            _addedBoxes = GetChanges(original, changed.Value);
            _deletedBoxes = GetChanges(changed.Value, original);
        }

        public override List<BoxesOverlay.BoxOverlayData> GetBoxesDatas()
        {
            var result = new List<BoxesOverlay.BoxOverlayData>();

            if (_addedBoxes is { } added &&
                added.Boxes.Count > 0 &&
                added.Parent.IsValid())
            {
                foreach (var box in added.Boxes)
                    result.Add(new BoxesOverlay.BoxOverlayData(added.Parent, box, Color.Green.WithAlpha(ColorAlpha)));
            }

            if (_deletedBoxes is { } deleted &&
                deleted.Boxes.Count > 0 &&
                deleted.Parent.IsValid())
            {
                foreach (var box in deleted.Boxes)
                    result.Add(new BoxesOverlay.BoxOverlayData(deleted.Parent, box, Color.Red.WithAlpha(ColorAlpha)));
            }

            return result;
        }

        private static (EntityUid Parent, List<Box2> Boxes) GetChanges(ZoneArgs original, ZoneArgs changed)
        {
            var originalParent = original.Parent;
            var changedParent = changed.Parent;

            var result = originalParent == changedParent
                ? Box2Helper.SubstructBoxes(changed.Area, original.Area)
                : [.. changed.Area];

            return (changedParent, result);
        }
    }

    public struct ZoneArgs()
    {
        public EntityUid Parent = EntityUid.Invalid;

        public EntProtoId<ZoneComponent> ProtoId = SharedZonesSystem.DefaultZoneProtoId;

        public List<Box2> Area = [];

        public string Name = string.Empty;

        public Color Color = Color.Gray;
    }
}
