// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.BoxLayout;
using Content.Client.SS220.Overlays;
using Content.Client.SS220.Zones.Systems;
using Content.Client.SS220.Zones.UI.CustomControls;
using Content.Client.Stylesheets;
using Content.Shared.Prototypes;
using Content.Shared.SS220.Maths;
using Content.Shared.SS220.Zones.Components;
using Content.Shared.SS220.Zones.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.SS220.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZoneEditor : PanelContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IBoxLayoutManager _boxLayoutManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ZonesSystem _zones = default!;

    public event Action<ZoneParams>? OnApply;
    public event Action<ZoneParams>? OnCancel;

    public ZoneParams? ChangedParams
    {
        get => _changedParams;
        set
        {
            _changedParams = value;
            CancelLayout();
            Refresh();
        }
    }
    private ZoneParams? _changedParams = default!;

    public ZoneParams OriginalParams { get; private set; } = default!;

    public ZoneParams CurrentParams => ChangedParams ?? OriginalParams;

    public ZoneEditorSetting EditorSetting { get; private set; } = ZoneEditorSetting.ReadWrite;

    private BoxLayoutMode _layoutMode = BoxLayoutMode.Adding;

    private readonly ZoneEditorBoxesOverlayProvider _overlayProvider;

    private readonly ZonePrototypeSelectorPopup _prototypeSelectorPopup = new();
    private readonly ZoneColorSelectorPopup _colorSelectorPopup = new();

    public ZoneEditor() : this(null) { }

    public ZoneEditor(Entity<ZoneComponent> ent, ZoneEditorSetting setting = ZoneEditorSetting.ReadWrite) : this(GetZoneParams(ent), setting) { }

    public ZoneEditor(ZoneParams? @params, ZoneEditorSetting setting = ZoneEditorSetting.ReadWrite)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var overlay = BoxesOverlay.GetOverlay();
        if (overlay.TryGetProvider<ZoneEditorBoxesOverlayProvider>(out var provider))
            _overlayProvider = provider;
        else
        {
            _overlayProvider = new()
            {
                Panel = this
            };
            overlay.AddProvider(_overlayProvider);
        }

        _zones = _entityManager.System<ZonesSystem>();

        SizeOptionsBackground.PanelOverride = new StyleBoxFlat()
        {
            BackgroundColor = new Color(32, 32, 32),
            BorderColor = new Color(128, 128, 128),
            BorderThickness = new Thickness(2)
        };

        PrototypeSelectorButton.AddStyleClass(StyleNano.StyleClassChatFilterOptionButton);
        ColorSelectorButton.AddStyleClass(StyleNano.StyleClassChatFilterOptionButton);

        ApplyButton.OnPressed += _ => OnApply?.Invoke(CurrentParams);
        CancelButton.OnPressed += _ => OnCancel?.Invoke(CurrentParams);

        InitInteractions();
        InitTooltips();

        SetEditorSetting(setting, refresh: false);
        SetOriginalParams(@params, refresh: false);
        Refresh();
    }

    private void InitInteractions()
    {
        AddBoxButton.OnToggled += e =>
        {
            if (e.Pressed)
                StartLayout(BoxLayoutMode.Adding);
            else
                CancelLayout();
        };
        CutBoxButton.OnToggled += e =>
        {
            if (e.Pressed)
                StartLayout(BoxLayoutMode.Cutting);
            else
                CancelLayout();
        };
        ShowChangesButton.OnToggled += e => SetOverlay(e.Pressed);

        ParentNetIDLineEdit.OnFocusExit += args => ChangeParent(args.Text);
        ParentNetIDLineEdit.OnTextEntered += args => ChangeParent(args.Text);

        NameLineEdit.OnFocusExit += args => ChangeName(args.Text);
        NameLineEdit.OnTextEntered += args => ChangeName(args.Text);

        PrototypeIDLineEdit.OnFocusExit += args => ChangeProtoID(args.Text);
        PrototypeIDLineEdit.OnTextEntered += args => ChangeProtoID(args.Text);

        HexColorLineEdit.OnFocusExit += args => ChangeColor(args.Text);
        HexColorLineEdit.OnTextEntered += args => ChangeColor(args.Text);

        AttachToLatticeCheckbox.OnPressed += _ => ChangeAttachToLattice(AttachToLatticeCheckbox.Pressed);

        PrototypeSelectorButton.OnPressed += _ =>
        {
            _prototypeSelectorPopup.Refresh();

            var globalPos = ColorSelectorButton.GlobalPosition;
            var box = UIBox2.FromDimensions(globalPos, _prototypeSelectorPopup.MinSize);
            _prototypeSelectorPopup.Open(box);
        };

        _prototypeSelectorPopup.OnPrototypeSelected += proto => ChangeProtoID(proto.ID);
        _prototypeSelectorPopup.OnVisibilityChanged += args => PrototypeSelectorButton.Pressed = args.Visible;

        ColorSelectorButton.OnPressed += _ =>
        {
            var color = CurrentParams.Color;
            _colorSelectorPopup.SetColor(color);

            var globalPos = ColorSelectorButton.GlobalPosition;
            var box = UIBox2.FromDimensions(globalPos, _colorSelectorPopup.MinSize);
            _colorSelectorPopup.Open(box);
        };

        _colorSelectorPopup.OnColorSelected += ChangeColor;
        _colorSelectorPopup.OnVisibilityChanged += args => ColorSelectorButton.Pressed = args.Visible;
    }

    private void InitTooltips()
    {
        NameLabel.ToolTip = Loc.GetString("zone-params-panel-name-tooltip");
        PrototypeIDLabel.ToolTip = Loc.GetString("zone-params-panel-prototype-id-tooltip");
        HexColorLabel.ToolTip = Loc.GetString("zone-params-panel-hex-color-tooltip");
        ParentNetIDLabel.ToolTip = Loc.GetString("zone-params-panel-container-net-id-tooltip");
        AttachToLatticeCheckbox.ToolTip = Loc.GetString("zone-params-panel-attach-to-grid-tooltip");
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _colorSelectorPopup.Close();
        RemoveLayoutReact();
        SetOverlay(false);
    }

    public void Refresh()
    {
        _prototypeSelectorPopup.Close();
        _colorSelectorPopup.Close();

        CancelLayout();

        var showedParams = CurrentParams;

        NameLineEdit.Text = showedParams.Name;
        PrototypeIDLineEdit.Text = showedParams.ProtoId;
        HexColorLineEdit.Text = showedParams.Color.ToHex();
        ParentNetIDLineEdit.Text = (showedParams.Parent is { } container && container.IsValid()) ? container.ToString() : string.Empty;
        AttachToLatticeCheckbox.Pressed = showedParams.AttachToLattice;

        Box2ListContainer.RemoveAllChildren();
        for (var i = 0; i < showedParams.Area.Count; i++)
        {
            var box = showedParams.Area[i];
            var entry = new ZoneBoxEntry(box);
            var index = i;
            entry.OnBoxChanged += newBox =>
            {
                var newArea = showedParams.Area.ToList();
                newArea[index] = newBox;
                ChangeArea(newArea);
            };
            Box2ListContainer.AddChild(entry);
        }

        RefreshEditable();
        _overlayProvider.Refresh();
    }

    public void ClearChanges()
    {
        ChangedParams = null;
    }

    public void SetOriginalParams(Entity<ZoneComponent> ent, bool refresh = true)
    {
        SetOriginalParams(GetZoneParams(ent, _entityManager), refresh);
    }

    public void SetOriginalParams(ZoneParams? @params, bool refresh = true)
    {
        OriginalParams = @params ?? new ZoneParams();

        if (refresh)
            Refresh();
    }

    private static ZoneParams GetZoneParams(Entity<ZoneComponent>? ent, IEntityManager? entityManager = null)
    {
        if (ent is null)
            return new ZoneParams();

        entityManager ??= IoCManager.Resolve<EntityManager>();

        entityManager.TryGetComponent<TransformComponent>(ent, out var xform);
        entityManager.TryGetComponent<MetaDataComponent>(ent, out var metaData);

        return new ZoneParams()
        {
            Parent = xform?.ParentUid ?? ent.Value,
            ProtoId = metaData?.EntityPrototype?.ID ?? SharedZonesSystem.DefaultZoneProtoId,
            Area = ent.Value.Comp.Area,
            Name = metaData?.EntityName ?? string.Empty,
            Color = ent.Value.Comp.Color,
            AttachToLattice = ent.Value.Comp.AttachToLattice
        };
    }

    private void StartLayout(BoxLayoutMode mode)
    {
        if (_boxLayoutManager.Active)
            return;

        _layoutMode = mode;

        switch (mode)
        {
            case BoxLayoutMode.Adding:
                _boxLayoutManager.StartNew();
                _boxLayoutManager.AttachToLattice = CurrentParams.AttachToLattice;
                break;

            case BoxLayoutMode.Cutting:
                _boxLayoutManager.StartNew();
                _boxLayoutManager.AttachToLattice = CurrentParams.AttachToLattice;
                _boxLayoutManager.SetColor(Color.Red);
                break;
        }

        AddLayotReact();
        _boxLayoutManager.SetOverlay(true);
    }

    private void CancelLayout()
    {
        if (!_boxLayoutManager.Active)
            return;

        _boxLayoutManager.Cancel();
    }

    private void AddLayotReact()
    {
        _boxLayoutManager.Ended += OnLayoutEnded;
        _boxLayoutManager.Cancelled += OnLayoutCancelled;
        _boxLayoutManager.SetOverlay(true);
    }

    private void RemoveLayoutReact()
    {
        _boxLayoutManager.Ended -= OnLayoutEnded;
        _boxLayoutManager.Cancelled -= OnLayoutCancelled;
        _boxLayoutManager.SetOverlay(false);

        AddBoxButton.Pressed = false;
        CutBoxButton.Pressed = false;
    }

    private void OnLayoutEnded(BoxLayoutManager.BoxArgs args)
    {
        var newParams = CurrentParams;
        if (!newParams.Parent.IsValid())
            newParams.Parent = args.Parent;
        else if (args.Parent != newParams.Parent)
        {
            CancelLayout();
            return;
        }

        var newArea = newParams.Area.ToList();
        switch (_layoutMode)
        {
            case BoxLayoutMode.Adding:
                newArea.Add(args.Box);
                break;

            case BoxLayoutMode.Cutting:
                var cutter = args.Box;
                newArea = [.. MathHelperExtensions.SubstructBox(newArea, cutter)];
                break;
        }

        newArea = [.. newArea.Select(b =>
        {
            var left = MathF.Round(b.Left, 2);
            var bottom = MathF.Round(b.Bottom, 2);
            var right = MathF.Round(b.Right, 2);
            var top = MathF.Round(b.Top, 2);
            return new Box2(left, bottom, right, top);
        })];

        newArea = [.. _zones.RecalculateArea(newArea, newParams.Parent, newParams.AttachToLattice)];
        newParams.Area = newArea;
        ChangeParams(_ => newParams);
    }

    private void OnLayoutCancelled()
    {
        RemoveLayoutReact();
        _boxLayoutManager.SetOverlay(false);
    }

    public void SetOverlay(bool active)
    {
        ShowChangesButton.Pressed = active;
        _overlayProvider.Active = active;
    }

    public void SetEditorSetting(ZoneEditorSetting setting, bool refresh = true)
    {
        EditorSetting = setting;

        if (refresh)
            Refresh();
    }

    private void RefreshEditable()
    {
        var editable = EditorSetting is ZoneEditorSetting.ReadWrite;

        NameLineEdit.Editable = editable;
        PrototypeIDLineEdit.Editable = editable;
        HexColorLineEdit.Editable = editable;
        ParentNetIDLineEdit.Editable = editable;

        AttachToLatticeCheckbox.Disabled = !editable;
        ApplyButton.Disabled = !editable;
        CancelButton.Disabled = !editable;
        AddBoxButton.Disabled = !editable;
        CutBoxButton.Disabled = !editable;

        foreach (var child in Box2ListContainer.Children)
        {
            if (child is not ZoneBoxEntry entry)
                continue;

            entry.Editable = editable;
        }
    }

    #region params changes
    private void ChangeParent(string parent)
    {
        if (!EntityUid.TryParse(parent, out var uid))
            return;

        ChangeParent(uid);
    }

    private void ChangeParent(EntityUid parent)
    {
        ChangeParams(cur =>
        {
            cur.Parent = parent;
            return cur;
        });
    }

    private void ChangeArea(List<Box2> area)
    {
        ChangeParams(cur =>
        {
            cur.Area = area;
            return cur;
        }, recalculate: true);
    }

    private void ChangeName(string name)
    {
        ChangeParams(cur =>
        {
            cur.Name = name;
            return cur;
        });
    }

    private void ChangeProtoID(EntProtoId<ZoneComponent> protoId)
    {
        if (!_prototype.TryIndex<EntityPrototype>(protoId, out var proto) ||
            !proto.HasComponent<ZoneComponent>())
            return;

        ChangeParams(cur =>
        {
            cur.ProtoId = protoId;
            return cur;
        });
    }

    private void ChangeColor(string hex)
    {
        if (!Color.TryParse(hex, out var color))
            return;

        ChangeColor(color);
    }

    private void ChangeColor(Color value)
    {
        ChangeParams(cur =>
        {
            cur.Color = value;
            return cur;
        });
    }

    private void ChangeAttachToLattice(bool value)
    {
        ChangeParams(cur =>
        {
            cur.AttachToLattice = value;
            return cur;
        }, recalculate: value);
    }

    private void ChangeParams(Func<ZoneParams, ZoneParams> func, bool refresh = true, bool recalculate = false)
    {
        if (EditorSetting is not ZoneEditorSetting.ReadWrite)
            return;

        var result = func.Invoke(CurrentParams);

        if (recalculate)
            result.Area = [.. _zones.RecalculateArea(result.Area, result.Parent, result.AttachToLattice)];

        _changedParams = result;
        if (refresh)
            Refresh();
    }
    #endregion

    private enum BoxLayoutMode
    {
        Adding,
        Cutting
    }

    public enum ZoneEditorSetting
    {
        ReadOnly,
        ReadWrite
    }

    private sealed class ZoneEditorBoxesOverlayProvider() : BoxesOverlay.BoxesOverlayProvider()
    {
        public ZoneEditor? Panel;
        private (EntityUid Parent, List<Box2> Boxes)? _addedBoxes;
        private (EntityUid Parent, List<Box2> Boxes)? _deletedBoxes;

        private const float ColorAlpha = 0.5f;

        public void Refresh()
        {
            _addedBoxes = null;
            _deletedBoxes = null;

            if (Panel == null)
                return;

            var changed = Panel.ChangedParams;
            if (changed == null)
                return;

            var original = Panel.OriginalParams;
            _addedBoxes = GetChanges(original, changed.Value);
            _deletedBoxes = GetChanges(changed.Value, original);
        }

        public override List<BoxesOverlay.BoxOverlayData> GetBoxesDatas()
        {
            var result = new List<BoxesOverlay.BoxOverlayData>();

            if (_addedBoxes is { } added &&
                added.Boxes.Count > 0 &&
                added.Parent.IsValid())
            {
                foreach (var box in added.Boxes)
                    result.Add(new BoxesOverlay.BoxOverlayData(added.Parent, box, Color.Green.WithAlpha(ColorAlpha)));
            }

            if (_deletedBoxes is { } deleted &&
                deleted.Boxes.Count > 0 &&
                deleted.Parent.IsValid())
            {
                foreach (var box in deleted.Boxes)
                    result.Add(new BoxesOverlay.BoxOverlayData(deleted.Parent, box, Color.Red.WithAlpha(ColorAlpha)));
            }

            return result;
        }

        private static (EntityUid Parent, List<Box2> Boxes) GetChanges(ZoneParams original, ZoneParams changed)
        {
            var originalParent = original.Parent;
            var changedParent = changed.Parent;

            var result = originalParent == changedParent
                ? [.. MathHelperExtensions.SubstructBoxes(changed.Area, original.Area)]
                : changed.Area.ToList();

            return (changedParent, result);
        }
    }

    public struct ZoneParams()
    {
        public EntityUid Parent = EntityUid.Invalid;

        public EntProtoId<ZoneComponent> ProtoId = SharedZonesSystem.DefaultZoneProtoId;

        public List<Box2> Area = [];

        public string Name = string.Empty;

        public Color Color = Color.Gray;

        public bool AttachToLattice = false;
    }
}
