using Content.Shared.SS220.Zones.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Zones.UI;

[GenerateTypedNameReferences]
public sealed partial class ZoneEntry : ContainerButton
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public Entity<ZoneComponent> Zone;

    public ZoneEntry(Entity<ZoneComponent> entity)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Zone = entity;
        Refresh();
    }

    public void Refresh()
    {
        IDLabel.Text = Zone.Owner.ToString();
        var name = "Unknown";
        if (_entityManager.TryGetComponent<MetaDataComponent>(Zone, out var meta) &&
            !string.IsNullOrEmpty(meta.EntityName) && !string.IsNullOrWhiteSpace(meta.EntityName))
            name = meta.EntityName;

        NameLabel.Text = name;
    }
}
