- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # SS220-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos #SS220-Transfer Detective To Security
  canBeAntag: true
  access:
  - Brig
  - Maintenance
#  - Service #SS220-Transfer Detective To Security
  - Detective
#  extendedAccess: #SS220-Transfer Detective To Security
  - Security

- type: startingGear
  id: DetectiveGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    neck: ClothingBeltHolsterFilled #SS220 holster to neck
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner
