- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # SS220-RoleTime
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  radioBold: true
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
#    belt: ClothingBeltSecurityFilled #SS220-FreedomHoSCap
    pocket1: WeaponPistolMk58Nonlethal #SS220-DeleteSecurityLetal-Begin
#    pocket2: MagazinePistol #SS220-DeleteSecurityLetal-End
  storage:
    back:
    - BoxSurvivalSecurity
    - Flash
    - MagazinePistolRubber #SS220-DeleteSecurityLetal-Begin
    - MagazinePistolRubber
    - FlashlightSeclite
    - DrinkRelaxingPeachCan #SS220-DeleteSecurityLetal-End
