- type: playTimeTracker
  id: JobGhostRole

- type: playTimeTracker
  id: AdminTime

- type: playTimeTracker
  id: AGhostTime

- type: playTimeTracker
  id: ObserverTime

- type: playTimeTracker
  id: EventRole

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorOfficer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobSeniorService
