using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpiderQueen;

[GenerateTypedNameReferences]
public sealed partial class SpiderQueenSpawnWindow : FancyWindow
{
    public SpiderQueenSpawnWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
