// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.TTS;
using Content.Shared.SS220.TTS.Requirements;
using Content.Shared.SS220.TTS.Systems;

namespace Content.Client.SS220.DialogWindowTtsVoicePreferencesUI;

/// <summary>
/// A modified <see cref="DialogWindow"/> window in which you can choose ProtoId for TTS voice
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class DialogWindowTtsVoicePreferences : FancyWindow
{
    private readonly string _promptFieldId;

    private bool _finished;

    public Action<string, TtsVoicePreferences>? OnConfirmed;

    public Action? OnCancelled;

    public DialogWindowTtsVoicePreferences(string title, string desc, QuickDialogEntry entry, TtsVoiceRequirementCheckData? voiceCheckData = null, TtsVoicePreferences? preferences = null, bool ok = true)
    {
        RobustXamlLoader.Load(this);

        Title = title;

        OkButton.Visible = ok;

        _promptFieldId = entry.FieldId;
        PromptLabel.Text = entry.Prompt;
        DescriptionLabel.Text = desc;

        preferences ??= SharedTtsSystem.DefaultVoicePreferences.Clone();
        TtsVoicePreferencesTable.SetPreferences(preferences, silent: true);
        TtsVoicePreferencesTable.RequirementsCheckData = voiceCheckData;

        OkButton.OnPressed += _ => Confirm();

        OnClose += () =>
        {
            if (!_finished)
                OnCancelled?.Invoke();
        };

        OpenCentered();
    }

    private void Confirm()
    {
        _finished = true;
        OnConfirmed?.Invoke(_promptFieldId, TtsVoicePreferencesTable.VoicePreferences);
        Close();
    }
}

