// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Economy;

[GenerateTypedNameReferences]
public sealed partial class EconomyBankingUiFragment : BoxContainer
{
    public EconomyBankingUiFragment()
    {
        RobustXamlLoader.Load(this);

        UpdateState(new EconomyBankingCartridgeUiState());
    }

    public void UpdateState(EconomyBankingCartridgeUiState state)
    {
        CardDefaultLabel.Visible = false;
        CardAbsentLabel.Visible = false;
        CardInvalidLabel.Visible = false;
        CardValidBox.Visible = false;

        switch (state.CardState)
        {
            case CardStateEnum.Default:
                CardDefaultLabel.Visible = true;
                break;
            case CardStateEnum.Absent:
                CardAbsentLabel.Visible = true;
                break;
            case CardStateEnum.Invalid:
                CardInvalidLabel.Visible = true;
                break;
            case CardStateEnum.Valid:
                CardValidBox.Visible = true;
                AccountIdLabel.Text = Loc.GetString("banking-program-ui-account-id-text", ("accountId", state.AccountId));
                AccountOwnerNameLabel.Text = state.OwnerName == string.Empty
                    ? string.Empty
                    : Loc.GetString("banking-program-ui-account-name-text", ("name", state.OwnerName));
                AccountBalanceLabel.Text = Loc.GetString("banking-program-ui-account-balance-text", ("balance", state.Balance));
                break;
        }
    }
}
