// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Shared.SS220.SuperMatter.Functions;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared.SS220.SuperMatter.Ui;
using Content.Client.SS220.UserInterface.PlotFigure;
using Content.Client.SS220.SuperMatter.Observer;
using System.Numerics;
using System.Linq;
using Robust.Client.Graphics;
using Content.Shared.Atmos;
using Robust.Client.UserInterface;
using Linguini.Syntax.Ast;

namespace Content.Client.SS220.SuperMatter.Ui;

// For optimization make cache value in ServerSystem and then subscribe from client if it needs it;
[GenerateTypedNameReferences]
public sealed partial class SuperMatterObserverMenu : FancyWindow
{
    [Dependency] ILocalizationManager _localization = default!;
    public event Action<BaseButton.ButtonEventArgs, SuperMatterObserverComponent>? OnServerButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, int>? OnCrystalButtonPressed;
    public SuperMatterObserverComponent? Observer;
    public int? CrystalKey;
    public Dictionary<Gas, Color> GasBarColors = new()
    {
        {Gas.Oxygen, Color.SeaBlue},
        {Gas.Nitrogen, Color.LightCoral},
        {Gas.Plasma, Color.Violet},
        {Gas.CarbonDioxide, Color.Gray}
    };
    public const int MAX_DATA_LENGTH = 180;
    public SuperMatterObserverMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        PlotValueOverTime.SetLabels(_localization.GetString("smObserver-plotXLabel-integrity"), _localization.GetString("smObserver-plotYLabel-integrity"), _localization.GetString("smObserver-plotTitle-integrity"));
        ColorState.MakeMeshgrid((1, 100, 25), (1, 100, 100));
        ColorState.EvalFunctionOnMeshgrid(GetIntegrityDamageMap);
        ColorState.SetLabels(_localization.GetString("smObserver-plotXLabel-colorState"), _localization.GetString("smObserver-plotYLabel-colorState"), _localization.GetString("smObserver-plotTitle-colorState"));
        InitGasRatioBars();
    }
    public void LoadState(List<Entity<SuperMatterObserverComponent>> observerEntities)
    {
        ServerNavigationBar.RemoveAllChildren();
        foreach (var (observerUid, observerComp) in observerEntities)
        {
            var serverButton = new ServerButton
            {
                Text = observerUid.ToString(),
                StyleBoxOverride = new StyleBoxFlat(Color.DarkGray),
                ObserverComponent = observerComp,
                Margin = new Thickness(2, 0, 2, 0),
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            serverButton.OnPressed += args =>
            {
                OnServerButtonPressed?.Invoke(args, serverButton.ObserverComponent);
            };
            ServerNavigationBar.AddChild(serverButton);
        }
    }
    public void LoadCrystal()
    {
        CrystalNavigationBar.RemoveAllChildren();
        if (Observer == null)
            return;
        foreach (var (crystalKey, name) in Observer.Names)
        {
            var crystalButton = new CrystalButton
            {
                Text = name,
                StyleBoxOverride = new StyleBoxFlat(Color.DarkGray),
                CrystalKey = crystalKey,
                ToggleMode = true,
                Margin = new Thickness(2, 0, 2, 0),
                StyleClasses = { "OpenBoth" }
            };

            crystalButton.OnPressed += args =>
            {
                OnCrystalButtonPressed?.Invoke(args, crystalButton.CrystalKey);
            };
            CrystalNavigationBar.AddChild(crystalButton);
        }
    }
    public void LoadCachedData()
    {
        if (Observer == null
            || CrystalKey == null)
            return;
        PlotValueOverTime.LoadPlot2DTimePoints(new PlotPoints2D(MAX_DATA_LENGTH, Observer.Integrities[CrystalKey.Value],
                                                        -1f, Observer.Integrities[CrystalKey.Value].Count));
        ColorState.LoadMovingPoint(new Vector2(Observer.Matters[CrystalKey.Value].Last().Value, Observer.InternalEnergy[CrystalKey.Value].Last().Value),
                                     new Vector2(Observer.Matters[CrystalKey.Value].Last().Derv, Observer.InternalEnergy[CrystalKey.Value].Last().Derv));
    }
    public void UpdateState(SuperMatterObserverUpdateState msg)
    {
        if (Observer == null
            || CrystalKey == null)
        {
            SetMessageDataToTextInfo();
            return;
        }
        if (msg.Id != CrystalKey)
            return;

        PlotValueOverTime.AddPointToPlot(new Vector2(PlotValueOverTime.GetLastAddedPointX() + 1f, msg.Integrity));
        ColorState.LoadMovingPoint(new Vector2(msg.Matter.Value, msg.InternalEnergy.Value), new Vector2(msg.Matter.Derivative, msg.InternalEnergy.Derivative));
        SetMessageDataToTextInfo(msg);
    }

    private void SetMessageDataToTextInfo(SuperMatterObserverUpdateState msg)
    {
        NameLabel.SetMessage(_localization.GetString("smObserver-name", ("name", msg.Name)));
        IntegrityLabel.SetMessage(_localization.GetString("smObserver-integrity", ("value", msg.Integrity)));
        PressureLabel.SetMessage(_localization.GetString("smObserver-pressure", ("value", msg.Pressure)));
        TemperatureLabel.SetMessage(_localization.GetString("smObserver-temperature", ("value", msg.Temperature)));
        MatterLabel.SetMessage(_localization.GetString("smObserver-matter", ("value", msg.Matter.Value)));
        InternalEnergyLabel.SetMessage(_localization.GetString("smObserver-internalEnergy", ("value", msg.InternalEnergy.Value)));
        DelamStatus.SetMessage(_localization.GetString("smObserver-delamStatus",
                                ("status", msg.Delaminate.Delaminates), ("ETA", msg.Delaminate.ETOfDelamination)));
    }
    private void SetMessageDataToTextInfo()
    {
        NameLabel.SetMessage(_localization.GetString("smObserver-integrity-none"));
        IntegrityLabel.SetMessage(_localization.GetString("smObserver-integrity-none"));
        PressureLabel.SetMessage(_localization.GetString("smObserver-pressure-none"));
        TemperatureLabel.SetMessage(_localization.GetString("smObserver-temperature-none"));
        MatterLabel.SetMessage(_localization.GetString("smObserver-matter-none"));
        InternalEnergyLabel.SetMessage(_localization.GetString("smObserver-internalEnergy-none"));
        DelamStatus.SetMessage(_localization.GetString("smObserver-delamStatus-none"));
    }
    private float GetIntegrityDamageMap(float matter, float internalEnergy)
    {
        return SuperMatterFunctions.EnergyToMatterDamageFactorFunction(
                    internalEnergy - SuperMatterFunctions.SafeInternalEnergyToMatterFunction(matter / SuperMatterFunctions.MatterNondimensionalization));
    }
    private void InitGasRatioBars()
    {
        foreach (var gas in Enum.GetValues<Gas>())
        {
            var gasBar = MakeGasRatioProgressBar(gas);
            GasContainer.AddChild(gasBar);
        }
    }
    private void UpdateGasRatioBars(Dictionary<Gas, float> gasRatios)
    {
        foreach (var gasBar in GasContainer.Children)
        {
            if (gasBar.GetType() != typeof(GasBar))
                return;

            ((ProgressBar)gasBar).SetAsRatio(gasRatios[((GasBar)gasBar).GasId]);
        }
    }
    private ProgressBar MakeGasRatioProgressBar(Gas gas)
    {

        if (TryGetStyleProperty<StyleBoxFlat>(ProgressBar.StylePropertyBackground, out var retBackground))
            retBackground.BackgroundColor = Color.FromHex("#2B2A26");
        else
            retBackground = new StyleBoxFlat(Color.FromHex("#2B2A26"));
        if (TryGetStyleProperty<StyleBoxFlat>(ProgressBar.StylePropertyForeground, out var retForeground))
            retForeground.BackgroundColor = GasBarColors.TryGetValue(gas, out var color) ? color : Color.ForestGreen;
        else
            retForeground = new StyleBoxFlat(GasBarColors.TryGetValue(gas, out var color) ? color : Color.ForestGreen);
        retForeground.BorderThickness = new Thickness(2f, 2f, 0f, 4f);
        retBackground.BorderThickness = new Thickness(2f, 2f, 0f, 4f);
        var gasBar = new GasBar
        {
            GasId = gas,
            HorizontalExpand = true,
            VerticalExpand = true,
            MinValue = 0f,
            MaxValue = 1f,
            MinHeight = 20f,
            Page = 0f,
            Value = 0.5f,
            BackgroundStyleBoxOverride = retBackground,
            ForegroundStyleBoxOverride = retForeground,
            MouseFilter = MouseFilterMode.Stop,
            TrackingTooltip = true,
            TooltipDelay = 0,
            ToolTip = gas + Environment.NewLine + gas.ToString(),
        };
        // gasBar.OnMouseEntered += _ =>;

        var gasLabel = new Label
        {
            Margin = new Thickness(2f, 2f, 0f, 14f),
            Text = gas.ToString(),
        };
        gasBar.AddChild(gasLabel);
        return gasBar;
    }
    private sealed class ServerButton : Button
    {
        public SuperMatterObserverComponent? ObserverComponent;
    }
    private sealed class CrystalButton : Button
    {
        public int CrystalKey;
    }
    private sealed class GasBar : ProgressBar
    {
        public Gas GasId;
    }
}


