name: Сообщить о проблеме с игровой картой
description: Если заметили недочёты на игровых картах
title: "[Проблема с картой] "
labels: []
assignees: []
body:
  - type: dropdown
    attributes:
      label: Выберите игровую карту
      options:
        - label: Frankenstein
          value: frankenstein
        - label: Axioma
          value: axioma
        - label: Astro
          value: astro
        - label: Eclipse
          value: eclipse
        - label: Donuts
          value: donuts
    required: true
  - type: textarea
    attributes:
      label: Опишите кратко о том, какую проблему вы обнаружили
      placeholder: Например, "На карте Axioma отсутствует текстура в области X."
    required: true
  - type: input
    attributes:
      label: Прикрепите изображение (если есть)
      description: Загрузите файл изображения, чтобы продемонстрировать проблему.
      placeholder: "Ссылка на изображение или путь к файлу"
    required: false

