- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  - Bagel
  - Barratry
  - CorvaxDelta
  - Box
#  - Cluster
#  - Core
#  - Fland
#  - Gemini
#  - Marathon
#  - Meta
#  - Omega
  - Origin
  # - Saltern
  # - Packed
