using Content.Shared.Ghost;
using Content.Shared.SS220.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using System.Numerics;

namespace Content.Client.SS220.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyMenuWindow : DefaultWindow
{
    private IEnumerable<BodyCont>? _bodies;

    public Action<NetEntity>? FollowBodyAction;
    public Action<NetEntity>? ToBodyAction;

    public GhostBodyMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }
    public void UpdateBodies(IEnumerable<BodyCont> bodies)
    {
        _bodies = bodies;
    }
    public void Populate()
    {
        Body.DisposeAllChildren();
        AddButtons();
    }

    private void AddButtons()
    {
        foreach (var body in _bodies ?? [])
        {
            //TODO: Перевести на карточки
            var bodyCard = new GhostBodyCard();
            bodyCard.Init(body);

            /*var currentButtonRef = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(340, 20),
                ClipText = true,
            };*/

            bodyCard.FollowBodyAction += FollowBodyAction;
            bodyCard.ToBodyAction += ToBodyAction;

            // currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);
            Body.AddChild(bodyCard);
        }
    }
}
