using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Ghost.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostAdditionGui : UIWidget
{
    public event Action? RespawnPressed;
    public event Action? ReturnToBodyPressed;

    public GhostBodyMenuWindow BodyMenuWindow { get; }
    public GhostAdditionGui()
    {
        RobustXamlLoader.Load(this);

        BodyMenuWindow = new GhostBodyMenuWindow();

        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
    }
}

