using Content.Client.SS220.Administration;
using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    [UsedImplicitly]
    public sealed partial class AntagonistsWindow : DefaultWindow
    {
        private PlayerInfo? _selectedAntagonist;

        public event Action<PlayerInfo?>? OnSelectionChanged;

        protected override void EnteredTree()
        {
            AntagonistsList.OnSelectionChanged += OnListOnOnSelectionChanged;
            ListOfTargetsButton.OnPressed += ListOfTargetsButtonOnPressed;
            //SS220-antag-add-objective begin
            //AddTargetButton.OnPressed += AddTargetButtonOnPressed;
            AddTargetButton.OnWindowCreated += AddTargetButtonOnWindowCreated;
            //SS220-antag-add-objective end
        }

        private void OnListOnOnSelectionChanged(PlayerInfo? obj)
        {
            _selectedAntagonist = obj;
            var disableButtons = _selectedAntagonist == null;
            ListOfTargetsButton.Disabled = disableButtons;
            AddTargetButton.Disabled = disableButtons; //SS220-antag-add-objective
        }

        private void ListOfTargetsButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            if (_selectedAntagonist == null)
                return;

            IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand(
                $"openobjectives {_selectedAntagonist.SessionId}");
        }

        //SS220-antag-add-objective begin
        private void AddTargetButtonOnWindowCreated(DefaultWindow window)
        {
            var addObjectiveWindow = (AddObjectiveWindow) window;
            if (_selectedAntagonist is null)
                return;
            var antagSession = IoCManager.Resolve<IPlayerManager>().GetSessionById(_selectedAntagonist.SessionId);
            addObjectiveWindow.SetAntagonist(antagSession);
        }
        //SS220-antag-add-objective end

        private void AddTargetButtonOnPressed(BaseButton.ButtonEventArgs obj)
        {
            if (_selectedAntagonist == null)
                return;

            //IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand(
            //    $"addtarget {_selectedAntagonist.EntityUid}");
        }
    }
}
