# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

# ss220 sec loadout update begin
- type: loadout
  id: JumpsuitHoSParadeMale
  equipment: JumpsuitHoSParadeMale

- type: startingGear
  id: JumpsuitHoSParadeMale
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: JumpskirtHoSParadeMale
  equipment: JumpskirtHoSParadeMale

- type: startingGear
  id: JumpskirtHoSParadeMale
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSParadeMale

- type: loadout
  id: JumpsuitHoSBlue
  equipment: JumpsuitHoSBlue

- type: startingGear
  id: JumpsuitHoSBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: JumpsuitHoSGrey
  equipment: JumpsuitHoSGrey

- type: startingGear
  id: JumpsuitHoSGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey
# ss220 sec loadout update end

# SS220-RemoveFormalSkirtLoadouts-Begin

#- type: loadout
#  id: HeadofSecurityFormalSkirt
#  equipment: HeadofSecurityFormalSkirt

#- type: startingGear
#  id: HeadofSecurityFormalSkirt
#  equipment:
#    jumpsuit: ClothingUniformJumpskirtHosFormal

# SS220-RemoveFormalSkirtLoadouts-End

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# ss220 sec loadout update begin
- type: loadout
  id: HatCapHoS
  equipment: HatCapHoS

- type: startingGear
  id: HatCapHoS
  equipment:
    head: ClothingHeadHatCapHoS
# ss220 sec loadout update end
# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment: ClothingNeckMantleHOS

- type: startingGear
  id: ClothingNeckMantleHOS
  equipment:
    neck: ClothingNeckMantleHOS

# ss220 sec loadout update begin
- type: loadout
  id: MantleHOSShoulder
  equipment: MantleHOSShoulder

- type: startingGear
  id: MantleHOSShoulder
  equipment:
    neck: ClothingNeckMantleHOSShoulder
# ss220 sec loadout update end

# OuterClothing
- type: loadout
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

# ss220 sec loadout update begin
- type: loadout
  id: WinterHoSUnarmored
  equipment: WinterHoSUnarmored

- type: startingGear
  id: WinterHoSUnarmored
  equipment:
    outerClothing: ClothingOuterWinterHoSUnarmored
# ss220 sec loadout update end
