// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using System.Diagnostics.CodeAnalysis;
using JetBrains.Annotations;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.SS220.SupaKitchen;
using Content.Client.Message;
using Robust.Shared.Utility;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.GameObjects;
using Content.Shared.FixedPoint;
using Robust.Client.Graphics;

namespace Content.Client.SS220.SupaKitchen.UI.Controls;

/// <summary>
///     Control for embedding a reagent into a guidebook.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideCookingRecipeEmbed : BoxContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntitySystemManager _entSysmMan = default!;

    private readonly SpriteSystem _spriteSystem;

    private HashSet<string> _nameSearchCache;

    private readonly ISawmill _sawmill;

    public GuideCookingRecipeEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entSysmMan.GetEntitySystem<SpriteSystem>();

        MouseFilter = MouseFilterMode.Stop;
        _sawmill = Logger.GetSawmill("KitchenCookbook");

        _nameSearchCache = new();
    }

    public GuideCookingRecipeEmbed(CookingRecipePrototype recipe) : this()
    {
        GenerateControl(recipe);
    }

    // uhhh shit i'm not sure about the performance
    public bool CheckMatchesSearch(string query)
    {
        foreach (var match in _nameSearchCache)
        {
            if (match.Contains(query))
                return true;
        }

        return false;
    }

    public void SetHiddenState(bool state, string query)
    {
        this.Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Recipe", out var id))
        {
            _sawmill.Error("Recipe embed tag is missing reagent prototype argument");
            return false;
        }

        if (!_prototype.TryIndex<CookingRecipePrototype>(id, out var recipe))
        {
            _sawmill.Error($"Specified CookingRecipe prototype \"{id}\" is not a valid CookingRecipe prototype");
            return false;
        }

        GenerateControl(recipe);

        control = this;
        return true;
    }

    private void GenerateControl(CookingRecipePrototype recipe)
    {
        if (!_prototype.TryIndex<EntityPrototype>(recipe.Result, out var product))
            return;

        _nameSearchCache.Add(product.Name);
        RecipeLabelTitle.SetMarkup(recipe.LocName);

        if (recipe.Color is { } color)
            NameBackground.PanelOverride = new StyleBoxFlat{ BackgroundColor = color };
        // reagents
        var reagentsMsg = new FormattedMessage();
        var reagentIngredientsCount = recipe.IngredientsReagents.Count;
        var u = 0;
        var reagentsLabel = new RichTextLabel()
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center
        };
        foreach (var (ingredientId, ingredientAmount) in recipe.IngredientsReagents)
        {
            if (!_prototype.TryIndex<ReagentPrototype>(ingredientId, out var ingredientProto))
            {
                reagentIngredientsCount--;
                continue;
            }

            var ingredientName = ingredientProto.LocalizedName;
            _nameSearchCache.Add(ingredientName);

            reagentsMsg.AddMarkupOrThrow(Loc.GetString("guidebook-cooking-recipes-ingredient-display",
                ("reagent", ingredientName), ("ratio", ingredientAmount)));

            u++;
            if (u < reagentIngredientsCount)
                reagentsMsg.PushNewline();
        }

        if (!reagentsMsg.IsEmpty)
        {
            reagentsMsg.Pop();
            reagentsLabel.SetMessage(reagentsMsg);
            IngredientsContainer.AddChild(reagentsLabel);
        }

        // solid ingredients
        foreach (var (ingredientId, ingredientAmount) in recipe.IngredientsSolids)
        {
            if (!_prototype.TryIndex<EntityPrototype>(ingredientId, out var ingredientProto))
                continue;

            var ingredientName = ingredientProto.Name;
            _nameSearchCache.Add(ingredientName);

            IngredientsContainer.AddChild(GetEntContainer(ingredientProto, ingredientAmount));
        }

        // output
        ProductsContainer.AddChild(GetEntContainer(product, 1));

        if (!_prototype.TryIndex<CookingInstrumentTypePrototype>(recipe.InstrumentType, out var instrumentProto))
            return;

        var instrumentMsg = new FormattedMessage();
        instrumentMsg.AddMarkupOrThrow(instrumentProto.Name);
        instrumentMsg.PushNewline();
        instrumentMsg.AddMarkupOrThrow(Loc.GetString("guidebook-cooking-recipes-timer-display", ("time", recipe.CookTime)));
        instrumentMsg.Pop();
        InstrumentName.SetMessage(instrumentMsg);

        if (instrumentProto.IconPath is not null)
            InstrumentIcon.TexturePath = instrumentProto.IconPath;
    }

    private BoxContainer GetEntContainer(EntityPrototype prototype, FixedPoint2 amount)
    {
        var entContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Center,
        };

        var entView = new EntityPrototypeView();
        entView.SetPrototype(prototype);
        entContainer.AddChild(entView);

        var entMsg = new FormattedMessage();
        entMsg.AddMarkupOrThrow(Loc.GetString("guidebook-cooking-recipes-ingredient-display",
                ("reagent", prototype.Name), ("ratio", amount)));
        entMsg.Pop();

        var entLabel = new RichTextLabel();
        entLabel.SetMessage(entMsg);
        entContainer.AddChild(entLabel);

        return entContainer;
    }
}
