// SS220 changeling Apex tracker
using System.Numerics;
using Content.Client.SS220.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared.Changeling.Mutations;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Changeling.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangelingApexTrackerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly SpriteSystem _sprite;
    private List<ChangelingApexTargetEntry> _targets = [];
    private string _searchText = string.Empty;

    public event Action<uint>? OnTargetSelected;

    public ChangelingApexTrackerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();
        SearchBar.OnTextChanged += OnSearchChanged;
    }

    public void SetTargets(List<ChangelingApexTargetEntry> targets)
    {
        _targets = targets;
        PopulateList();
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _searchText = args.Text.Trim();
        PopulateList();
    }

    private void PopulateList()
    {
        TargetList.RemoveAllChildren();

        foreach (var target in _targets)
        {
            JobIconPrototype? jobIcon = null;
            if (target.JobIcon is { } iconId)
                _prototype.TryIndex(iconId, out jobIcon);

            var jobName = jobIcon?.LocalizedJobName ?? string.Empty;
            if (!target.Name.Contains(_searchText, StringComparison.OrdinalIgnoreCase) &&
                !jobName.Contains(_searchText, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var button = new ShapeButton
            {
                ToolTip = string.IsNullOrEmpty(jobName)
                    ? target.Name
                    : Loc.GetString(
                        "changeling-apex-window-entry-tooltip",
                        ("name", target.Name),
                        ("job", jobName)),
                StyleClasses = { "OpenBoth" },
                SetHeight = 36,
                Radius = 8,
                BorderThickness = 2f,
                Margin = new Thickness(5, 0, 5, 5),
                HorizontalExpand = true,
            };

            if (jobIcon != null)
            {
                button.AddChild(new TextureRect
                {
                    Texture = _sprite.Frame0(jobIcon.Icon),
                    TextureScale = new Vector2(2f, 2f),
                    ModulateSelfOverride = Color.White,
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Center,
                });
            }

            button.AddChild(new Label
            {
                Text = target.Name,
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Center,
            });
            button.OnPressed += _ => OnTargetSelected?.Invoke(target.SelectionToken);
            TargetList.AddChild(button);
        }

        if (TargetList.ChildCount == 0)
        {
            TargetList.AddChild(new Label
            {
                Text = Loc.GetString("changeling-apex-window-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(5),
            });
        }
    }
}
