- type: job
  id: SecurityBorg
  name: job-name-secborg
  description: job-description-secborg
  experienceDefinition: StationBorgsRoleExperience
  playTimeTracker: JobSecBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      role: JobBorg
      time: 20h 
    - !type:OverallPlaytimeRequirement
      role: Security
      time: 20h
  canBeAntag: false
  icon: JobIconSecBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgChassisSecurityBattery
  applyTraits: false
  special: #SS220-RenameStart - start
  - !type:AddComponentSpecial
    components:
    - type: RenameStart #SS220-RenameStart - end