- type: job
  id: SecurityBorg
  name: job-name-security-borg
  description: job-description-security-borg
  experienceDefinition: StationBorgsRoleExperience
  playTimeTracker: JobSecurityBorg
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 20h 
  - !type:DepartmentTimeRequirement
    role: Security
    time: 20h
  canBeAntag: false
  icon: JobIconSecBorg
  supervisors: job-supervisors-hos
  jobEntity: PlayerBorgChassisSecurityBattery
  applyTraits: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: RenameStart