// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AntagonistsWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _clientConsoleHost = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private PlayerInfo? _selectedAntagonist;

    public AntagonistsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        AntagonistsList.OnSelectionChanged += OnListOnOnSelectionChanged;
        ListOfTargetsButton.OnPressed += ListOfTargetsButtonOnPressed;
        AddTargetButton.OnWindowCreated += AddTargetButtonOnWindowCreated;
    }

    private void OnListOnOnSelectionChanged(PlayerInfo? obj)
    {
        _selectedAntagonist = obj;
        var disableButtons = _selectedAntagonist == null;
        ListOfTargetsButton.Disabled = disableButtons;
        AddTargetButton.Disabled = disableButtons;
    }

    private void ListOfTargetsButtonOnPressed(BaseButton.ButtonEventArgs _)
    {
        if (_selectedAntagonist == null)
            return;

        _clientConsoleHost.ExecuteCommand(
            $"openobjectives {_selectedAntagonist.SessionId}");
    }

    private void AddTargetButtonOnWindowCreated(DefaultWindow window)
    {
        if (_selectedAntagonist is null)
            return;

        var addObjectiveWindow = (AddObjectiveWindow) window;
        if (!_playerManager.TryGetSessionById(_selectedAntagonist.SessionId, out var antagSession))
            return;

        addObjectiveWindow.SetAntagonist(antagSession);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        AntagonistsList.OnSelectionChanged -= OnListOnOnSelectionChanged;
        ListOfTargetsButton.OnPressed -= ListOfTargetsButtonOnPressed;
        AddTargetButton.OnWindowCreated -= AddTargetButtonOnWindowCreated;
    }
}
