#Svarshik's missing mags
- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderLightRifle
  result: SpeedLoaderLightRifle
  materials:
    Steel: 75

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifle
  result: MagazineBoxCaselessRifle
  materials:
    Steel: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  materials:
    Steel: 60

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumIncendiary
  result: MagazineMagnumIncendiary
  materials:
    Steel: 180
    Plastic: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumUranium
  result: MagazineMagnumUranium
  materials:
    Steel: 60
    Plastic: 150
    Uranium: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacityEmpty
  result: MagazinePistolHighCapacityEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHighCapacity
  result: MagazinePistolHighCapacity
  materials:
    Steel: 240

- type: latheRecipe
  id: WeaponTaser
  result: WeaponTaser
  completetime: 5
  materials:
    Steel: 700
    Plastic: 300

- type: latheRecipe
  id: WeaponLaserSMG
  result: WeaponLaserSMG
  completetime: 5
  materials:
    Steel: 2000
    Plastic: 1000
    Gold: 500
    Plasma: 1000

- type: latheRecipe
  id: WeaponLaserPistol
  result: WeaponLaserPistol
  completetime: 5
  materials:
    Steel: 1000
    Glass: 200
    Plastic: 1200

- type: latheRecipe
  id: LaserSMGPowerCell
  result: LaserSMGPowerCell
  completetime: 5
  materials:
    Steel: 300
    Glass: 200
    Plastic: 300
    Gold: 50

- type: latheRecipe
  id: WeaponPowerCell
  result: WeaponPowerCell
  completetime: 5
  materials:
    Steel: 300
    Glass: 200
    Plastic: 300

- type: latheRecipe
  id: RiotLaserShield
  result: RiotLaserShieldAlt
  completetime: 5
  materials:
    Steel: 900
    Plastic: 300

- type: latheRecipe
  id: RiotBulletShield
  result: RiotBulletShieldAlt
  completetime: 5
  materials:
    Steel: 900
    Plastic: 300
    Uranium: 700

- type: latheRecipe
  id: TaserCartridge
  result: MagazineTaser
  completetime: 1
  materials:
    Steel: 50 # Very cheap because it's weak
    Plastic: 50

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxAntiMaterielAP
  result: MagazineBoxAntiMaterielAP
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxAntiMaterielHP
  result: MagazineBoxAntiMaterielHP
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineRifleHP
  result: MagazineRifleHP
  materials:
    Steel: 25
    Plastic: 300

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxRifleHP
  result: MagazineBoxRifleHP
  materials:
    Plastic: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineLightRifleHP
  result: MagazineLightRifleHP
  materials:
    Steel: 25
    Plastic: 360

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxLightRifleHP
  result: MagazineBoxLightRifleHP
  materials:
    Plastic: 600

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolHP
  result: MagazinePistolHP
  materials:
    Steel: 25
    Plastic: 65

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazinePistolSubMachineGunHP
  result: MagazinePistolSubMachineGunHP
  materials:
    Steel: 25
    Plastic: 250

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxPistolHP
  result: MagazineBoxPistolHP
  materials:
    Plastic: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: SpeedLoaderMagnumHP
  result: SpeedLoaderMagnumHP
  materials:
    Steel: 50
    Plastic: 150

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxMagnumHP
  result: MagazineBoxMagnumHP
  materials:
    Plastic: 240

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunHP
  result: MagazineShotgunHP
  materials:
    Steel: 100
    Plastic: 190

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: BoxShotgunHP
  result: BoxShotgunHP
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunHEI
  result: MagazineShotgunHEI
  materials:
    Steel: 100
    Plastic: 190

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: BoxShotgunHEI
  result: BoxShotgunHEI
  materials:
    Steel: 240
    Plastic: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineShotgunExplosive
  result: MagazineShotgunExplosive
  materials:
    Steel: 50
    Plastic: 90
    Plasma: 80

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: BoxShotgunHE
  result: BoxShotgunHE
  materials:
    Steel: 240
    Plastic: 160
    Plasma: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxAntiMaterielHE
  result: MagazineBoxAntiMaterielHE
  materials:
    Steel: 240
    Plastic: 160
    Plasma: 150

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineAntiMaterialFMJ
  result: MagazineAntiMaterialFMJ
  materials:
    Steel: 120
    Plastic: 160

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineAntiMaterialExplosive
  result: MagazineAntiMaterialExplosive
  materials:
    Steel: 240
    Plastic: 160
    Plasma: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineAntiMaterialAP
  result: MagazineAntiMaterialAP
  materials:
    Steel: 240
    Plastic: 160
    Uranium: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineAntiMaterialHP
  result: MagazineAntiMaterialHP
  materials:
    Steel: 90
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineFullRifleFMJ
  result: MagazineFullRifleFMJ
  materials:
    Steel: 90
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineFullRifleAP
  result: MagazineFullRifleAP
  materials:
    Steel: 90
    Plastic: 80
    Uranium: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineFullRifleHP
  result: MagazineFullRifleHP
  materials:
    Steel: 90
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineFullRifleIncendiary
  result: MagazineFullRifleIncendiary
  materials:
    Steel: 90
    Plastic: 80

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxFullRifleFMJ
  result: MagazineBoxFullRifleFMJ
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxFullRifleAP
  result: MagazineBoxFullRifleAP
  materials:
    Steel: 200
    Uranium: 180

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxFullRifleHP
  result: MagazineBoxFullRifleHP
  materials:
    Steel: 200

- type: latheRecipe
  parent: BaseAmmoBoxRecipe
  id: MagazineBoxFullRifleIncendiary
  result: MagazineBoxFullRifleIncendiary
  materials:
    Steel: 150
    Plastic: 180

- type: latheRecipe
  parent: [ BaseGoldCircuitboardRecipe, BaseMachineRecipeCategory ]
  id: ShuttleGunMLGSWCircuitboard
  result: ShuttleGunMLGSWCircuitboard
  completetime: 12

- type: latheRecipe
  id: WeaponEnergyTurretSecurityMachineCircuitboard
  result: WeaponEnergyTurretSecurityMachineCircuitboard
  completetime: 5
  materials:
    Glass: 400
    Gold: 400
    Silver: 400
    Plasma: 200

- type: latheRecipe
  id: WeaponEnergyTurretSecurityControlPanelElectronics
  result: WeaponEnergyTurretSecurityControlPanelElectronics
  completetime: 5
  materials:
    Glass: 400
    Gold: 400
    Silver: 400
    Plasma: 200
