// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Silicons.Laws;
using Content.Shared.SS220.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Silicons.Laws;

[GenerateTypedNameReferences]
public sealed partial class LawUploadWindow : FancyWindow
{
    // SS220 random lawset begin
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    // SS220 random lawset end

    public event Action<LawUploadTarget, int>? OnApply;
    public event Action<string>? OnEject;
    private int _revision;

    //ss220 random lawset begin
    private static readonly Color Cyan = Color.FromHex("#79CEDC");
    private static readonly Color Amber = Color.FromHex("#E6B86A");
    private static readonly Color Muted = Color.FromHex("#ACBAC6");
    private ProtoId<SiliconLawPrototype>[]? _aiLaws;
    private ProtoId<SiliconLawPrototype>[]? _borgLaws;
    private ProtoId<SiliconLawPrototype>[]? _boardLaws;
    //ss220 random lawset end

    public LawUploadWindow()
    {
        RobustXamlLoader.Load(this);
        // SS220 random lawset
        IoCManager.InjectDependencies(this);
        //ss220 random lawset begin
        HeaderPanel.PanelOverride = PanelStyle("#1C2C38", Cyan);
        AccessPanel.PanelOverride = PanelStyle("#222C36", Color.FromHex("#415363"));
        CurrentPanel.PanelOverride = PanelStyle("#202A34", Cyan);
        BoardPanel.PanelOverride = PanelStyle("#272B32", Amber);
        UploadPanel.PanelOverride = PanelStyle("#222C36", Color.FromHex("#415363"));
        CurrentTabs.SetTabTitle(0, Loc.GetString("law-upload-tab-ai"));
        CurrentTabs.SetTabTitle(1, Loc.GetString("law-upload-tab-borgs"));
        //ss220 random lawset end
        EjectCard.OnPressed += _ => OnEject?.Invoke(LawUploadConsoleComponent.CardSlot);
        EjectBoard.OnPressed += _ => OnEject?.Invoke(LawUploadConsoleComponent.BoardSlot);
        ApplyAi.OnPressed += _ => Apply(LawUploadTarget.Ai);
        ApplyBorgs.OnPressed += _ => Apply(LawUploadTarget.Borgs);
        ApplyAll.OnPressed += _ => Apply(LawUploadTarget.All);
    }

    private void Apply(LawUploadTarget target)
    {
        ApplyAi.Disabled = ApplyBorgs.Disabled = ApplyAll.Disabled = true;
        OnApply?.Invoke(target, _revision);
    }

    public void UpdateState(LawUploadState state)
    {
        // SS220 random lawset begin
        _revision = state.Revision;

        //ss220 random lawset begin
        var statusColor = state.CanApply ? Color.FromHex("#8BD4A4") :
            state.Status is "law-upload-no-power" or "law-upload-no-station" or "law-upload-access-denied"
                ? Color.FromHex("#F08B85")
                : Amber;
        StatusBadge.Text = Loc.GetString(state.CanApply ? "law-upload-status-ready" : "law-upload-status-blocked");
        StatusBadge.FontColorOverride = statusColor;
        CardStatus.SetMessage(Loc.GetString(state.HasCard ? "law-upload-card-present" : "law-upload-card-missing"), Muted);
        Status.SetMessage(Loc.GetString(state.Status));
        AiTitle.SetMessage(LawsetName(state.AiLawset), Cyan);
        BorgTitle.SetMessage(LawsetName(state.BorgLawset), Cyan);
        UpdateLawRows(AiLaws, state.AiLaws, ref _aiLaws, Cyan, "law-upload-no-laws");
        UpdateLawRows(BorgLaws, state.BorgLaws, ref _borgLaws, Cyan, "law-upload-no-laws");
        BoardTitle.SetMessage(state.HasBoard
            ? LawsetName(state.BoardLawset)
            : Loc.GetString("law-upload-board-empty"), Amber);
        UpdateLawRows(BoardLaws, state.BoardLaws, ref _boardLaws, Amber, "law-upload-board-help");
        AiCount.Text = Loc.GetString("law-upload-law-count", ("count", state.AiLaws.Length));
        BorgCount.Text = Loc.GetString("law-upload-law-count", ("count", state.BorgLaws.Length));
        BoardCount.Text = Loc.GetString("law-upload-law-count", ("count", state.BoardLaws.Length));
        //ss220 random lawset end

        EjectCard.Disabled = !state.HasCard;
        EjectBoard.Disabled = !state.HasBoard;
        ApplyAi.Disabled = ApplyBorgs.Disabled = ApplyAll.Disabled = !state.CanApply;
        // SS220 random lawset end
    }

    // SS220 random lawset begin
    private string LawsetName(ProtoId<SiliconLawsetPrototype> id)
    {
        // SS220 random lawset
        if (string.IsNullOrEmpty(id.Id))
            return string.Empty;

        if (!_prototypes.TryIndex(id, out var prototype))
            return string.Empty;

        return prototype.Name is { } name ? Loc.GetString(name) : id.Id;
    }

    //ss220 random lawset begin
    private void UpdateLawRows(BoxContainer container, ProtoId<SiliconLawPrototype>[] laws,
        ref ProtoId<SiliconLawPrototype>[]? previous, Color accent, string emptyMessage)
    {
        // Preserve scroll position and controls when only authorization/status changes.
        if (previous != null && previous.SequenceEqual(laws))
            return;

        previous = laws.ToArray();
        container.RemoveAllChildren();
        if (laws.Length == 0)
        {
            var empty = new RichTextLabel { Margin = new Thickness(8, 16) };
            empty.SetMessage(Loc.GetString(emptyMessage), Muted);
            container.AddChild(empty);
            return;
        }

        for (var i = 0; i < laws.Length; i++)
        {
            var law = _prototypes.Index(laws[i]);
            var row = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat(Color.FromHex(i % 2 == 0 ? "#18222C" : "#1D2832")),
                HorizontalExpand = true,
            };
            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 10,
                Margin = new Thickness(8, 10),
            };
            content.AddChild(new Label
            {
                Text = law.LawIdentifierOverride ?? law.Order.ToString(),
                FontColorOverride = accent,
                MinWidth = 28,
                VerticalAlignment = VAlignment.Top,
            });
            var text = new RichTextLabel { HorizontalExpand = true };
            text.SetMessage(Loc.GetString(law.LawString));
            content.AddChild(text);
            row.AddChild(content);
            container.AddChild(row);
        }
    }

    private static StyleBoxFlat PanelStyle(string background, Color accent) => new()
    {
        BackgroundColor = Color.FromHex(background),
        BorderColor = accent,
        BorderThickness = new Thickness(0, 2, 0, 0),
    };
    //ss220 random lawset end
    // SS220 random lawset end
}
