- type: liquidSplattersSettings
  id: liquidSplattersSettingsDefault
  clothingSolutionScale: 0.15
  damageSolutionScale: 0.3
  clothingSlotChances:
    outerClothing: 0.5
    jumpsuit: 0.7
    gloves: 0.9
    head: 0.5
    mask: 0.9
