- type: liquidSplattersSettings
  id: liquidSplattersSettingsDefault
  weaponContainerIncrement: 1
  clothingContainerIncrement: 1
  clothingSlotChances:
    outerClothing: 0.5
    jumpsuit: 0.7
    gloves: 0.9
    head: 0.5
    mask: 0.9
