// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.Virology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.Virology;

[GenerateTypedNameReferences]
public sealed partial class VaccinatorWindow : DefaultWindow
{
    [Dependency] private IGameTiming _timing = default!;

    private TimeSpan? _operationEnd;
    private TimeSpan _operationDuration;
    private VirologyMachineStatus _status;

    public VaccinatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ScanProgress.Progress = ComputeProgress();
    }

    private float ComputeProgress()
    {
        if (_status == VirologyMachineStatus.Scanning && _operationEnd is { } end && _operationDuration > TimeSpan.Zero)
        {
            var remaining = (end - _timing.CurTime) / _operationDuration;
            return Math.Clamp(1f - (float)remaining, 0f, 1f);
        }

        return _status is VirologyMachineStatus.Printing or VirologyMachineStatus.Result ? 1f : 0f;
    }

    public void UpdateState(VaccinatorBoundUserInterfaceState state)
    {
        _operationEnd = state.OperationEnd;
        _operationDuration = state.OperationDuration;
        _status = state.Status;
        ScanProgress.Progress = ComputeProgress();

        StationLabel.Text = state.StationName is { } station
            ? Loc.GetString("pathology-console-station", ("name", station))
            : Loc.GetString("pathology-console-station-unknown");

        StatusLabel.Text = state.Status switch
        {
            VirologyMachineStatus.NoSample => Loc.GetString("vaccinator-no-sample"),
            VirologyMachineStatus.Scanning => Loc.GetString("vaccinator-scanning"),
            VirologyMachineStatus.Printing => Loc.GetString("vaccinator-printing"),
            VirologyMachineStatus.Result => Loc.GetString("vaccinator-result"),
            _ => Loc.GetString("vaccinator-ready"),
        };

        ResultsContainer.DisposeAllChildren();
        foreach (var virus in state.Viruses)
            ResultsContainer.AddChild(BuildVirusBlock(virus));

        BufferLabel.Text = Loc.GetString("vaccinator-buffer", ("amount", state.BufferTricordrazine));

        var idleWithSample = state.Status is VirologyMachineStatus.Ready or VirologyMachineStatus.Result;
        var hasResult = state.Status == VirologyMachineStatus.Result;
        ScanButton.Disabled = !idleWithSample;
        TransferButton.Disabled = !idleWithSample;
        CreateVaccineButton.Disabled = !hasResult;
        PrintButton.Disabled = !hasResult;
    }

    private static BoxContainer BuildVirusBlock(VaccinatorVirusResult virus)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 0, 0, 6),
        };

        box.AddChild(new Label
        {
            Text = virus.Name != null
                ? Loc.GetString("vaccinator-virus-name", ("name", virus.Name))
                : Loc.GetString("vaccinator-virus-unknown"),
        });

        if (virus.Suppressed)
            box.AddChild(new Label { Text = Loc.GetString("vaccinator-suppressed") });

        foreach (var symptom in virus.Symptoms)
            box.AddChild(new Label { Text = $" · {symptom}", Margin = new Thickness(4, 0, 0, 0) });

        if (virus.UnreadableCount > 0)
            box.AddChild(new Label
            {
                Text = Loc.GetString("vaccinator-unreadable", ("count", virus.UnreadableCount)),
                StyleClasses = { "LabelSubText" },
            });

        if (virus.CureReagents.Count > 0 || virus.CureHidden)
            box.AddChild(new Label
            {
                Text = virus.CureReagents.Count > 0
                    ? Loc.GetString("vaccinator-cure", ("reagents", string.Join(", ", virus.CureReagents)))
                    : Loc.GetString("vaccinator-cure-hidden"),
            });

        return box;
    }
}
