// © SS220, MIT full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/MIT_LICENSE.TXT

using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;

namespace Content.Client.SS220.ResourceMiner;

[GenerateTypedNameReferences]
public sealed partial class ResourceMinerWindow : FancyWindow
{
    [Dependency] private readonly ILocalizationManager _localization = default!;

    public event Action<int>? OnChangeSiloOption;
    public event Action? OnRequestSilos;

    public ResourceMinerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        NetSiloOptions.OnItemSelected += (args) => OnChangeSiloOption?.Invoke(args.Id);
        UpdateButton.OnPressed += (_) => OnRequestSilos?.Invoke();
    }

    public void SetAvailableSilos(HashSet<NetEntity> silos)
    {
        NetSiloOptions.Clear();

        foreach (var silo in silos)
        {
            NetSiloOptions.AddItem(silo.ToString(), silo.Id);
        }
    }
}
