- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # SS220-RoleTime
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
#    jumpsuit: ClothingUniformJumpsuitPsychologist #SS220-Psychologist-Loadoust-Fix
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - BoxSurvivalMedical
