// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Item;
using Content.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.SS220.Administration.UI.ManageDelivery;

[GenerateTypedNameReferences]
public sealed partial class DeliveryContentsWindow : DefaultWindow
{
    public event Action<string>? OnReplace;
    public event Action? OnClear;

    [Dependency] private IPrototypeManager _prototypeManager = default!;

    private DeliveryItemData? _selected;
    private bool _loaded;

    public DeliveryContentsWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ContentsList.SearchBar = SearchEdit;
        ContentsList.DataFilterCondition += Filter;
        ContentsList.GenerateItem += GenerateRow;
        ContentsList.ItemPressed += OnItemPressed;
        ContentsList.NoItemSelected += ClearSelection;

        SearchEdit.OnTextChanged += OnSearchChanged;
        SearchClearButton.OnPressed += OnSearchClearPressed;

        ClearButton.OnPressed += _ => OnClear?.Invoke();

        ReplaceButton.OnPressed += OnReplacePressed;

        OnOpen += () =>
        {
            if (_loaded)
                return;

            _loaded = true;
            ContentsList.PopulateList(LoadItems());
        };
    }

    private void OnSearchChanged(LineEditEventArgs args)
    {
        SearchClearButton.Disabled = string.IsNullOrEmpty(args.Text);
    }

    private void OnSearchClearPressed(BaseButton.ButtonEventArgs args)
    {
        SearchEdit.SetText("", invokeEvent: true);
    }

    private List<DeliveryItemData> LoadItems()
    {
        var items = new List<DeliveryItemData>();

        foreach (var prototype in _prototypeManager.EnumeratePrototypes<EntityPrototype>())
        {
            if (prototype.Abstract || prototype.HideSpawnMenu)
                continue;

            if (!prototype.HasComponent<ItemComponent>())
                continue;

            var label = string.IsNullOrEmpty(prototype.Name) ? prototype.ID : prototype.Name;
            if (!string.IsNullOrWhiteSpace(prototype.EditorSuffix))
                label += $" [{prototype.EditorSuffix}]";

            items.Add(new DeliveryItemData(prototype.ID, label, prototype.Description));
        }

        items.Sort((a, b) =>
        {
            var byLabel = string.Compare(a.Label, b.Label, StringComparison.CurrentCultureIgnoreCase);
            return byLabel != 0
                ? byLabel
                : string.Compare(a.Id.Id, b.Id.Id, StringComparison.CurrentCultureIgnoreCase);
        });

        return items;
    }

    private static bool Filter(string search, ListData data)
    {
        if (data is not DeliveryItemData item)
            return false;

        return item.Label.Contains(search, StringComparison.OrdinalIgnoreCase)
               || item.Id.Id.Contains(search, StringComparison.OrdinalIgnoreCase);
    }

    private void GenerateRow(ListData data, ListContainerButton button)
    {
        if (data is not DeliveryItemData item)
            return;

        var icon = new EntityPrototypeView
        {
            MinSize = new Vector2(32, 32),
            MaxSize = new Vector2(32, 32),
        };
        icon.SetPrototype(item.Id);

        button.AddChild(new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
            Children =
            {
                icon,
                new Label
                {
                    Text = item.Label,
                    ClipText = true,
                    HorizontalExpand = true,
                },
            },
        });

        button.ToolTip = string.IsNullOrEmpty(item.Description)
            ? item.Id.Id
            : $"{item.Id.Id}\n{item.Description}";

        button.AddStyleClass(ListContainer.StyleClassListContainerButton);
    }

    private void OnItemPressed(BaseButton.ButtonEventArgs args, ListData data)
    {
        _selected = data as DeliveryItemData;
        ReplaceButton.Disabled = _selected == null;
    }

    private void ClearSelection()
    {
        _selected = null;
        ReplaceButton.Disabled = true;
    }

    private void OnReplacePressed(BaseButton.ButtonEventArgs args)
    {
        if (_selected == null)
            return;

        OnReplace?.Invoke(_selected.Id);
    }
}

public sealed record DeliveryItemData(EntProtoId Id, string Label, string? Description) : ListData;

