// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.Administration;
using Content.Shared.CrewManifest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.ManageDelivery;

[GenerateTypedNameReferences]
public sealed partial class ManageDeliveryWindow : DefaultWindow
{
    public event Action<int>? OnApplyReward;
    public event Action<uint?>? OnApplyRecipient;
    public event Action<int>? OnApplyTimer;

    private List<(uint, CrewManifestEntry)> _crew = [];
    private uint? _selectedRecordId;
    private bool _hasTimer;

    public ManageDeliveryWindow()
    {
        RobustXamlLoader.Load(this);

        RewardSpinBox.InitDefaultButtons();
        RewardSpinBox.IsValid = value => value >= 0;

        ApplyRewardButton.OnPressed += _ => OnApplyReward?.Invoke(RewardSpinBox.Value);

        TimerSpinBox.SetButtons([-60, -10], [10, 60]);
        TimerSpinBox.IsValid = seconds => seconds >= 0;

        ApplyTimerButton.OnPressed += _ => OnApplyTimer?.Invoke(TimerSpinBox.Value);

        CrewList.OnItemSelected += _ => SelectCrewItem();
        CrewList.OnItemDeselected += _ => SelectCrewItem();
        SearchCrew.OnTextChanged += _ => RefreshCrewList();

        ApplyRecipientButton.OnPressed += _ => OnApplyRecipient?.Invoke(_selectedRecordId);
    }

    public void UpdateState(ManageDeliveryEuiState state)
    {
        TargetLabel.Text = Loc.GetString("admin-verbs-delivery-target", ("name", state.TargetName));
        RewardSpinBox.OverrideValue(state.BaseSpesoReward);

        _hasTimer = state.HasTimer;
        TimerSpinBox.OverrideValue(state.TimeLeftSeconds);
        TimerHintLabel.Text = state.HasTimer
            ? Loc.GetString("admin-verbs-delivery-timer-current",
                ("time", TimeSpan.FromSeconds(state.TimeLeftSeconds).ToString("mm\\:ss")))
            : Loc.GetString("admin-verbs-delivery-timer-none");
        UpdateTimerButton();

        CurrentRecipientLabel.Text = Loc.GetString("admin-verbs-delivery-recipient-current",
            ("name", state.RecipientName ?? Loc.GetString("delivery-recipient-no-name")),
            ("job", state.RecipientJobTitle ?? Loc.GetString("delivery-recipient-no-job")));

        _selectedRecordId = null;

        _crew = state.Crew;
        RefreshCrewList();
    }

    private void UpdateTimerButton()
    {
        ApplyTimerButton.Disabled = !_hasTimer;
    }

    private void RefreshCrewList()
    {
        var search = SearchCrew.Text;

        CrewList.Clear();

        foreach (var (id, entry) in _crew)
        {
            if (!string.IsNullOrWhiteSpace(search) && !Matches(entry, search))
                continue;

            CrewList.AddItem($"{entry.Name} ({entry.JobTitle})").Metadata = id;
        }

        SelectCrewItem();
    }

    private static bool Matches(CrewManifestEntry entry, string search)
    {
        return entry.Name.Contains(search, StringComparison.OrdinalIgnoreCase)
               || entry.JobPrototype.Contains(search, StringComparison.OrdinalIgnoreCase)
               || entry.JobTitle.Contains(search, StringComparison.OrdinalIgnoreCase);
    }

    private void SelectCrewItem()
    {
        _selectedRecordId = CrewList.GetSelected().FirstOrDefault() is { } item
            ? (uint) item.Metadata!
            : null;

        ApplyRecipientButton.Disabled = _selectedRecordId == null;
    }
}

