- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]

- type: antagSpecifier
  parent: RestrictedAntag
  id: SpaceNinja
  spawnerPrototype: SpawnPointGhostSpaceNinja
  pickPlayer: false
  startingGear: SpaceNinjaGear
  roleLoadout:
  - RoleSurvivalSpaceNinja
  briefing:
    text: ninja-role-greeting
    color: Green
    sound: /Audio/Misc/ninja_greeting.ogg
  components:
  - type: SpaceNinja
  - type: NpcFactionMember
    factions:
    - Syndicate
  - type: AutoImplant
    implants:
    - DeathAcidifierImplant
  - type: RandomMetadata
    nameSegments:
    - NamesNinjaTitle
    - NamesNinja
    nameFormat: name-format-ninja
  mindRoles:
  - MindRoleNinja

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  experienceDefinition: NinjaRoleExperience # SS220-experience-update
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSpaceNinja # SS220 Ninja Resprite
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinja
    id: PassengerPDA # ss220 remove ninja pda
    ears: ClothingHeadsetNinja
    pocket1: DoubleEmergencyOxygenTankFilled # SS220 Ninja Resprite
    pocket2: PinpointerStation
    belt: EnergyKatana
  inhand:
    - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - Crowbar
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool
    - BoxSurvivalEngineering # SS220 Ninja Resprite
    - EmergencyMedipen
    - Flare
    - FoodSnackNutribrick
    - DrinkWaterBottleFull

- type: chameleonOutfit
  id: NinjaChameleonOutfit
  name: roles-antag-space-ninja-name
  icon: "JobIconNinja"
  startingGear: SpaceNinjaGear
  equipment:
    neck: ClothingNeckGoldmedal
