- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  objective: roles-antag-initial-infected-objective
  guides: [ Zombies ]
  #SS220 Add antags playtime trackers begin
  playTimeTracker: AntagInitialInfected
  antagColor: Plum
  #SS220 Add antags playtime trackers end
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 180000 # 50h SS220 time

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
