using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostAdditionGui : UIWidget
{
    public event Action? RespawnPressed;
    public event Action? ReturnToBodyPressed;

    public GhostBodyMenuWindow BodyMenuWindow { get; }

    public GhostAdditionGui()
    {
        RobustXamlLoader.Load(this);

        BodyMenuWindow = new GhostBodyMenuWindow();

        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke();
        BodyMenuButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
    }

    public void SetRespawnRemainTimer(TimeSpan respawnRemainTime)
    {
        if (respawnRemainTime > TimeSpan.Zero)
        {
            RespawnButton.Text = $"{Loc.GetString("mind-ext-respawn-button")}" +
                $" {respawnRemainTime.Minutes}:{respawnRemainTime.Seconds}";
            RespawnButton.Disabled = true;
        }
        else
        {
            RespawnButton.Text = Loc.GetString("mind-ext-respawn-button");
            RespawnButton.Disabled = false;
        }

    }

    public void LockRespawnTimer()
    {
        RespawnButton.Text = Loc.GetString("mind-ext-respawn-button");
        RespawnButton.Disabled = true;
    }
}

