using Content.Shared.SS220.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyCard : UIWidget
{
    public Action<NetEntity>? FollowBodyAction;
    public Action<NetEntity>? ToBodyAction;

    private BodyCont _body;
    public GhostBodyCard()
    {
        RobustXamlLoader.Load(this);
    }
    public void Init(BodyCont body)
    {
        _body = body;

        BodyNameLabel.Text = body.MetaData.EntityName;
        BodyDescriptionLabel.Text = body.MetaData.EntityDescription;

        BodyStateLabel.FontColorOverride = Color.Red;

        switch (body.State)
        {
            case BodyStateToEnter.Avaible:
                FollowButton.Disabled = false;
                ToBodyButton.Disabled = false;

                BodyStateLabel.FontColorOverride = Color.Green;
                BodyStateLabel.Text = "(Доступен)";
                break;
            case BodyStateToEnter.Abandoned:
                FollowButton.Disabled = false;
                BodyStateLabel.Text = "(Безвозвратно вами покинут)";
                break;
            case BodyStateToEnter.Engaged:
                FollowButton.Disabled = false;
                BodyStateLabel.Text = "(Занят другим игроком)";
                break;
            case BodyStateToEnter.InCryo:
                BodyStateLabel.Text = "(Помещен в криохранилище)";
                break;
            case BodyStateToEnter.Destroyed:
                BodyStateLabel.Text = "(Уничтожен)";
                break;
        }

        FollowButton.OnButtonDown += _ => FollowBodyAction?.Invoke(_body.Id);

        ToBodyButton.OnButtonDown += _ => ToBodyAction?.Invoke(_body.Id);

    }
}
