using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostAdditionGui : UIWidget
{
    public event Action? RespawnPressed;
    public event Action? ReturnToBodyPressed;

    public GhostBodyMenuWindow BodyMenuWindow { get; }

    public GhostAdditionGui()
    {
        RobustXamlLoader.Load(this);

        BodyMenuWindow = new GhostBodyMenuWindow();

        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke();
        BodyMenuButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();

        BodyMenuButton.Text = Loc.GetString("mind-ext-body-menu-button");
    }

    public void SetRespawnTimer(TimeSpan respawnTime, TimeSpan currentTime)
    {
        if (respawnTime > currentTime)
        {
            RespawnButton.Text = $"{Loc.GetString("mind-ext-respawn-button")}" +
                $" {respawnTime.Minutes}:{respawnTime.Seconds}";
            RespawnButton.Disabled = true;
        }
        else
        {
            RespawnButton.Text = Loc.GetString("mind-ext-respawn-button");
            RespawnButton.Disabled = false;
        }

    }
}

