using Content.Client.Administration.UI.CustomControls;
using Content.Shared.SS220.MindExtension;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyCard : UIWidget
{
    public Action<NetEntity>? FollowBodyAction;
    public Action<NetEntity>? ToBodyAction;

    private TrailPoint _body;
    public GhostBodyCard()
    {
        RobustXamlLoader.Load(this);
    }
    public void Init(TrailPoint body)
    {
        _body = body;

        BodyNameLabel.Text = body.MetaData.EntityName;
        BodyDescriptionLabel.Text = body.MetaData.EntityDescription;

        BodyStateLabel.FontColorOverride = Color.Red;

        switch (body.State)
        {
            case BodyStateToEnter.Avaible:
                FollowButton.Disabled = false;
                ToBodyButton.Disabled = false;

                BodyStateLabel.FontColorOverride = Color.Green;
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-avaible");
                break;
            case BodyStateToEnter.Abandoned:
                FollowButton.Disabled = false;
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-abandoned");
                if (body.ByAdmin)
                {
                    ToBodyButton.Disabled = false;
                    BodyStateLabel.FontColorOverride = Color.Yellow;
                }
                break;
            case BodyStateToEnter.Engaged:
                FollowButton.Disabled = false;
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-engaged");
                if (body.ByAdmin)
                {
                    ToBodyButton.Disabled = false;
                    BodyStateLabel.FontColorOverride = Color.Yellow;
                }
                break;
            case BodyStateToEnter.InCryo:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-incryo");
                break;
            case BodyStateToEnter.Destroyed:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-destroyed");
                break;
        }


        FollowButton.OnButtonDown += _ => FollowBodyAction?.Invoke(_body.Id);

        ToBodyButton.OnButtonDown += _ => ToBodyAction?.Invoke(_body.Id);

    }
}
