using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostAdditionGui : UIWidget
{
    public event Action? RespawnPressed;
    public event Action? ReturnToBodyPressed;

    public GhostBodyMenuWindow BodyMenuWindow { get; }

    public GhostAdditionGui()
    {
        RobustXamlLoader.Load(this);

        BodyMenuWindow = new GhostBodyMenuWindow();

        RespawnButton.OnPressed += _ => RespawnPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
    }

    public void SetRespawnTimer(TimeSpan respawnTime, TimeSpan currentTime)
    {
        if (respawnTime > currentTime)
        {
            RespawnButton.Text = $"В лобби {respawnTime.Minutes}:{respawnTime.Seconds}";
            RespawnButton.Disabled = true;
        }
        else
        {
            RespawnButton.Text = $"В лобби";
            RespawnButton.Disabled = false;
        }

    }
}

