// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.SS220.MindExtension;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyCard : UIWidget
{
    public Action<NetEntity>? FollowBodyAction;
    public Action<NetEntity>? ToBodyAction;
    public Action<NetEntity>? DeleteTrailPointAction;

    private TrailPoint _body;

    private readonly Color _availableColorConst = Color.Green;
    private readonly Color _adminAvailableColorConst = Color.Green;
    private readonly Color _unavailableColorConst = Color.Green;

    public GhostBodyCard()
    {
        RobustXamlLoader.Load(this);
    }
    public void Init(TrailPoint body)
    {
        _body = body;

        BodyNameLabel.Text = body.MetaData.EntityName;
        BodyDescriptionLabel.Text = body.MetaData.EntityDescription;

        switch (body.State)
        {
            case BodyStateToEnter.Available:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-available");
                SetAvailableState();
                break;
            case BodyStateToEnter.Abandoned:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-abandoned");

                if (body.ByAdmin)
                    SetAdminAvailableState();
                else
                    SetUnavailableState();

                break;
            case BodyStateToEnter.Engaged:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-engaged");

                if (body.ByAdmin)
                    SetAdminAvailableState();
                else
                    SetUnavailableState();

                break;
            case BodyStateToEnter.InCryo:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-incryo");
                SetInvalidState();
                break;
            case BodyStateToEnter.Destroyed:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-destroyed");
                SetInvalidState();
                break;
        }


        FollowButton.OnButtonDown += _ => FollowBodyAction?.Invoke(_body.Id);
        ToBodyButton.OnButtonDown += _ => ToBodyAction?.Invoke(_body.Id);
        DeleteButton.OnButtonDown += OnDeleteButtonDown;
    }

    private void OnDeleteButtonDown(BaseButton.ButtonEventArgs args)
    {
        var field = "line";
        var prompt = Loc.GetString("mind-ext-dialog-delete-trail-poitnt-desc");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt);
        var entries = new List<QuickDialogEntry> { entry };
        var dialog = new DialogWindow(Loc.GetString("mind-ext-dialog-delete-trail-poitnt-title"), entries);

        dialog.OnConfirmed += _ => DeleteTrailPointAction?.Invoke(_body.Id);
    }

    private void SetAvailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = false;

        BodyStateLabel.FontColorOverride = _availableColorConst;
    }

    private void SetAdminAvailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = false;

        BodyStateLabel.FontColorOverride = _adminAvailableColorConst;
    }

    private void SetUnavailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = true;

        BodyStateLabel.FontColorOverride = _unavailableColorConst;
    }

    private void SetInvalidState()
    {
        FollowButton.Disabled = true;
        ToBodyButton.Disabled = true;

        BodyStateLabel.FontColorOverride = _unavailableColorConst;
    }
}
