// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CultYogg.MiGo.UI;

[GenerateTypedNameReferences]
public sealed partial class MiGoTeleportTarget : BoxContainer
{
    public MiGoTeleportTarget(NetEntity? target, string name)
    {
        RobustXamlLoader.Load(this);

        if (target.HasValue)
        {
            DollView.SetEntity(target.Value);
        }

        NameLabel.Text = name;
    }
}
