// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CultYogg.MiGo.UI;

[GenerateTypedNameReferences]
public sealed partial class MiGoTeleportTarget : BoxContainer
{
    public NetEntity? TargetNetEnt;
    public MiGoTeleportTarget(string name, NetEntity? target)
    {
        RobustXamlLoader.Load(this);

        Panel.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#343536") };

        if (target.HasValue)
        {
            TargetNetEnt = target.Value;
            //DollView.SetEntity(target.Value); //for better visualisation,  maybe later
        }

        NameLabel.Text = name;//cause center aligment isnt working
    }
}
