- type: latheRecipe
  id: RiotLaserShield
  result: RiotLaserShieldAlt
  parent: BaseShieldRecipe
  completetime: 5
  materials:
    Steel: 900
    Plastic: 300

- type: latheRecipe
  id: RiotBulletShield
  result: RiotBulletShieldAlt
  parent: BaseShieldRecipe
  completetime: 5
  materials:
    Steel: 900
    Plastic: 300
    Uranium: 700

