// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Text;
using Content.Client.Message;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class OperationDescription : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private SurgeryGraphSystem _surgeryGraph = default!;

    private bool _dataLocked = false;
    public bool DataLocked
    {
        get => _dataLocked;
        set
        {
            _dataLocked = value;
            LockIcon.Visible = value;
        }
    }

    private const string NodeTabulation = "  ";
    private const string EdgeTabulation = "  - ";

    private readonly LocId _nodeNameText = "operation-description-node-name-text";

    public OperationDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _surgeryGraph = _entityManager.System<SurgeryGraphSystem>();
    }

    public void ShowDescription(ProtoId<SurgeryGraphPrototype> id)
    {
        if (DataLocked)
            return;

        OperationContainer.RemoveAllChildren();

        if (!_prototypeManager.Resolve(id, out var surgeryProto))
        {
            OperationName.Text = "#err-cant-index";
            Description.Text = null;
            return;
        }

        OperationName.Text = Loc.GetString(surgeryProto.Name);

        var surgeryDescription = new RichTextLabel();
        surgeryDescription.SetMarkup(Loc.GetString(surgeryProto.Description));
        OperationContainer.AddChild(surgeryDescription);

        AddOperationSteps(surgeryProto);
    }

    private void AddOperationSteps(SurgeryGraphPrototype graph)
    {
        var nodes = graph.Nodes;

        foreach (var node in nodes)
        {
            var nodeRichText = new RichTextLabel();
            nodeRichText.SetMarkup(Loc.GetString(_nodeNameText, ("nodeName", Loc.GetString(node.Name))));
            nodeRichText.MouseFilter = MouseFilterMode.Stop;
            AddNodeInfo(node, nodeRichText);

            OperationContainer.AddChild(nodeRichText);
        }
    }

    private void AddNodeInfo(SurgeryGraphNode node, RichTextLabel nodeLabel)
    {
        if (node.Edges.Count == 0)
            return;

        var builder = new StringBuilder();

        foreach (var edge in node.Edges)
        {
            builder.Append(NodeTabulation);
            builder.Append(Loc.GetString("operation-description-edge-to", ("to", edge.Target)));
            AddConditionInfo(edge, builder);
        }

        nodeLabel.ToolTip = builder.ToString();
    }

    private void AddConditionInfo(SurgeryGraphEdge edge, StringBuilder builder)
    {
        var surgeryRequirements = _surgeryGraph.GetRequirements(edge);

        if (surgeryRequirements.Count == 0)
            return;

        builder.AppendLine(Loc.GetString("operation-description-condition-section-name"));

        foreach (var requirement in surgeryRequirements)
        {
            var info = requirement.RequirementDescription(_prototypeManager, _entityManager);
            builder.Append(EdgeTabulation);
            builder.AppendLine(info);
        }
    }
}
