// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Text;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class OperationDescription : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private SurgeryGraphSystem _surgeryGraph = default!;

    private bool _dataLocked = false;
    public bool DataLocked
    {
        get => _dataLocked;
        set
        {
            _dataLocked = value;
            LockIcon.Visible = value;
        }
    }

    public string NodeDataTabulation = "\t";
    public string EdgeDataTabulation = "\t\t";

    public string NodeSeparator = "----";

    public OperationDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _surgeryGraph = _entityManager.System<SurgeryGraphSystem>();
    }

    public void ShowDescription(ProtoId<SurgeryGraphPrototype> id)
    {
        if (DataLocked)
            return;

        if (!_prototypeManager.Resolve(id, out var surgeryProto))
        {
            OperationName.Text = "#err-cant-index";
            Description.Text = null;
            return;
        }

        OperationName.Text = Loc.GetString(surgeryProto.Name);

        StringBuilder builder = new();

        builder.AppendLine(Loc.GetString(surgeryProto.Description));
        AddOperationSteps(surgeryProto, builder);

        Description.Text = builder.ToString();
    }

    private void AddOperationSteps(SurgeryGraphPrototype graph, StringBuilder builder)
    {
        var nodes = graph.Nodes;

        foreach (var node in nodes)
        {
            AddNodeInfo(node, builder);
            builder.AppendLine(NodeSeparator);
        }

        builder.Remove(builder.Length - NodeSeparator.Length, NodeSeparator.Length);
    }

    private void AddNodeInfo(SurgeryGraphNode node, StringBuilder builder)
    {
        if (node.Edges.Count == 0)
            return;

        builder.Append(NodeDataTabulation);
        builder.AppendLine(Loc.GetString("operation-description-node-name", ("name", node.Name)));

        var surgeryNodeDescription = _surgeryGraph.Description(node) is null ?
                                        "#err" :
                                        Loc.GetString(_surgeryGraph.Description(node)!);

        builder.AppendLine(surgeryNodeDescription);

        foreach (var edge in node.Edges)
        {
            builder.Append(NodeSeparator);
            builder.AppendLine(Loc.GetString("operation-description-edge-to", ("to", edge.Target)));
            AddConditionInfo(edge, builder);
        }
    }

    private void AddConditionInfo(SurgeryGraphEdge edge, StringBuilder builder)
    {
        var surgeryRequirements = _surgeryGraph.GetRequirements(edge);

        if (surgeryRequirements.Count == 0)
            return;

        builder.AppendLine(Loc.GetString("operation-description-condition-section-name"));

        foreach (var requirement in surgeryRequirements)
        {
            var info = requirement.RequirementDescription(_prototypeManager, _entityManager);
            builder.Append(EdgeDataTabulation);
            builder.AppendLine(info);
        }
    }
}
