// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Text;
using Content.Shared.SS220.Surgery.Graph;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class OperationDescription : BoxContainer
{
    [Dependency] private readonly PrototypeManager _prototypeManager = default!;

    public bool DataLocked = false;

    public OperationDescription()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void MakeDescription(ProtoId<SurgeryGraphPrototype> id)
    {
        if (DataLocked)
            return;

        var surgeryProto = _prototypeManager.Index(id);

        OperationName.Text = Loc.GetString(surgeryProto.NameLocPath);

        StringBuilder builder = new();

        builder.Append(Loc.GetString(surgeryProto.DescriptionLocPath));

        AddOperationSteps(surgeryProto, builder);

        OperationDescription.Text = builder.ToString();
    }

    private void AddOperationSteps(SurgeryGraphPrototype graph, StringBuilder builder)
    {
        // TODO
    }
}
