// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class PatientStatus : Control
{
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;

    public PatientStatus()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void ShowStatus(PatientStatusData data)
    {
        if (data.OverallDamage >= 0)
            OverallDamage.Text = data.OverallDamage.ToString();

        if (data.PatientState != Shared.Mobs.MobState.Invalid)
            MobStatus.Text = Loc.GetString($"patient-status-mob-state-{data.PatientState}");

        if (data.BodyDecayDegree >= 0)
            DecayDegree.Text = _localizationManager.TryGetString($"patient-status-decay-degree-{data.BodyDecayDegree}", out var locStr)
                                ? locStr : data.BodyDecayDegree.ToString();

        if (data.BrainRotDegree >= 0)
            BrainRotStatus.Text = Loc.GetString($"patient-status-brain-rot-degree", ("degree", data.BrainRotDegree));
    }
}
