// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Text;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Surgery.UiParts;

[GenerateTypedNameReferences]
public sealed partial class TreatmentSuggestion : BoxContainer
{
    public string InSectionTextTabulation = "  ";

    public TreatmentSuggestion()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void ShowSuggestion(TreatmentRecommendation recommendation)
    {
        StringBuilder builder = new();

        AddSection(recommendation.Problems, Loc.GetString("treatment-recommendation-problem-section-name"), builder);
        AddSection(recommendation.Operations, Loc.GetString("treatment-recommendation-operation-section-name"), builder);
        AddSection(recommendation.Suggestions, Loc.GetString("treatment-recommendation-suggestion-section-name"), builder);

        TreatmentSuggestionText.Text = builder.ToString();
    }

    private void AddSection(List<string> data, string sectionName, StringBuilder builder)
    {
        if (data.Count == 0)
            return;

        builder.Append(sectionName);

        foreach (var text in data)
        {
            builder.AppendLine();
            builder.AppendJoin(InSectionTextTabulation, text);
        }
    }
}
