// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.CriminalRecords;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Diagnostics;
using System.Linq;

namespace Content.Client.SS220.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class CriminalRecordsWindow : FancyWindow
{
    private readonly IEntitySystemManager _sysMan;
    private readonly IPrototypeManager _prototype;
    private readonly SpriteSystem _sprite;

    private bool _isPopulating = false;

    private readonly Color _altEntryColor = Color.FromHex("#151519");
    private readonly Color _defaultLineColor = Color.FromHex("#808080");
    private readonly StyleBoxFlat _indicatorOverride;
    private bool _securityMode = true;
    private bool _creationMode = false;
    public int MaxEntryMessageLength = 200;

    public Action<(string, ProtoId<CriminalStatusPrototype>?)>? OnCriminalStatusChange;
    public Action<int>? OnCriminalStatusDelete;
    public Action<(NetEntity, uint)?>? OnKeySelected;

    public CriminalRecordsWindow()
    {
        RobustXamlLoader.Load(this);

        _prototype = IoCManager.Resolve<IPrototypeManager>();
        _sysMan = IoCManager.Resolve<IEntitySystemManager>();
        _sprite = _sysMan.GetEntitySystem<SpriteSystem>();

        //Logger.DebugS("TEST", "==CREATING WINDOW!==");

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating)
            {
                //Logger.DebugS("TEST","REEEEEEEETURN" + (_isPopulating ? ": POPULATING" : ""));
                return;
            }

            //Logger.DebugS("SENT KEY!", "=====SENT KEY!");
            OnKeySelected?.Invoke(args.Metadata.Key);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
            {
                //Logger.DebugS("SENT KEY!", "=====UNSELECTED!");
                OnKeySelected?.Invoke(null);
            }
            else
            {
                //Logger.DebugS("SENT KEY!", "=====TRIED UNSELECTED BUT POPULATING!");
            }
        };

        ExpandButton.OnPressed += ToggleExpand;
        CreationExpandButton.OnPressed += ToggleExpand;

        ChangeStatusButton.OnPressed += ToggleCreation;
        CancelRecordCreationButton.OnPressed += ToggleCreation;

        SaveRecordCreationButton.OnPressed += _ =>
        {
            var text = Rope.Collapse(MessageInput.TextRope).Trim();
            ProtoId<CriminalStatusPrototype>? statusTypeId = null;
            if (StatusTypeSelector.SelectedMetadata is string cast)
                statusTypeId = new(cast);

            OnCriminalStatusChange?.Invoke((text, statusTypeId));
            ToggleCreation();
        };

        StatusTypeSelector.OnItemSelected += args =>
        {
            StatusTypeSelector.Select(args.Id);
        };

        CancelRecordCreationButton.StyleClasses.Add(StyleBase.ButtonOpenLeft);
        CancelRecordCreationButton.StyleClasses.Add(StyleBase.ButtonCaution);

        RecordSearch.OnTextChanged += OnSearchChanged;
        _indicatorOverride = new StyleBoxFlat()
        {
            BackgroundColor = _defaultLineColor
        };
        StatusColorIndicator.PanelOverride = _indicatorOverride;

        MessageInput.Placeholder = new Rope.Leaf(Loc.GetString("criminal-records-ui-message-placeholder"));
        //MessageInput.OnKeyBindDown += _ => MessageInputChanged(); // Doesn't work 24.09.2023 textedit is broken

        SetupStatusTypeSelector();
    }

    // public void MessageInputChanged()
    // {
    //     if (MessageInput.TextLength >= MaxEntryMessageLength)
    //     {
    //         var newtext = Rope.Collapse(MessageInput.TextRope);
    //         newtext = newtext.Substring(0, (int) MathF.Min(MaxEntryMessageLength, newtext.Length));

    //         MessageInput.CursorPosition = new TextEdit.CursorPos(MessageInput.CursorPosition.Index-1, MessageInput.CursorPosition.Bias);
    //         MessageInput.TextRope = new Rope.Leaf(newtext);
    //     }
    // }

    public void SetupStatusTypeSelector()
    {
        var statuses = _prototype.EnumeratePrototypes<CriminalStatusPrototype>().ToList();

        // no status
        StatusTypeSelector.AddItem(Loc.GetString("criminal-records-ui-no-status"));

        foreach (var status in statuses)
        {
            StatusTypeSelector.AddItem(status.Name);
            StatusTypeSelector.SetItemMetadata(StatusTypeSelector.ItemCount - 1, status.ID);
        }
    }

    public void SetSecurityMode(bool mode)
    {
        RecordHistoryPanel.Visible = mode;
        _securityMode = mode;
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        RecordListing.Filter = args.Text;
        RecordListing.RebuildList();
    }

    public void ToggleExpand(BaseButton.ButtonEventArgs? _ = null)
    {
        Details.Visible = !Details.Visible;
        var newIcon = Details.Visible
        ? "/Textures/SS220/Interface/Misc/up.png"
        : "/Textures/SS220/Interface/Misc/down.png";
        ExpandButton.IconTexture = newIcon;
        CreationExpandButton.IconTexture = newIcon;
    }

    public void ToggleCreation(BaseButton.ButtonEventArgs? _ = null)
    {
        _creationMode = !_creationMode;
        RecordHistoryPanel.Visible = !_creationMode;
        RecordCreationPanel.Visible = _creationMode;

        if (!_creationMode)
        {
            MessageInput.TextRope = new Rope.Leaf("");
        }
    }

    public void UpdateState(CriminalRecordConsoleState state)
    {
        // Logger.DebugS("TEST", "WINDOW GOT STATE!");
        if (state.RecordListing != null)
            PopulateRecordListing(state.RecordListing, state.SelectedKey);

        if (state.SelectedRecord != null)
        {
            //Logger.DebugS("STATUS", "=====SELECTED!");
            CharacterName.Text = state.SelectedRecord.Name;
            Details.LoadRecordDetails(state.SelectedRecord);
            PopulateRecords(state.SelectedRecord);
            PanelRightPlaceholder.Visible = false;
            PanelRight.Visible = true;
        }
        else
        {
            //Logger.DebugS("STATUS", "=====NO SELECTED!");
            CharacterName.Text = "Не выбрана запись";
            PanelRightPlaceholder.Visible = true;
            PanelRight.Visible = false;
        }
    }

    private void PopulateRecordListing(Dictionary<(NetEntity, uint), CriminalRecordShort>? listing, (NetEntity, uint)? selected)
    {
        if (_isPopulating)
            return;

        //Logger.DebugS("TEST", "POPULATING LIST!");

        _isPopulating = true;

        RecordListing.SetItems(listing, selected);

        _isPopulating = false;

        //RecordListing.SortItemsByText();
    }

    private void PopulateRecords(GeneralStationRecord record)
    {
        CriminalRecordContainer.DisposeAllChildren();

        if (record.CriminalRecords is not { } catalog)
            return;

        var keyList = catalog.Records.Keys.ToList();
        keyList.Sort();

        for (var i = 0; i < keyList.Count; i++)
        {
            var time = keyList[i];
            CriminalRecord entry = catalog.Records[time];
            var entryDisplay = new CriminalRecordDisplay();

            Texture? iconTexture = null;
            if (entry.RecordType != null &&
            _prototype.TryIndex<CriminalStatusPrototype>(entry.RecordType, out var statusProto))
            {
                if (statusProto.StatusIcon != null &&
                _prototype.TryIndex<StatusIconPrototype>(statusProto.StatusIcon, out var statusIconProto))
                {
                    iconTexture = _sprite.Frame0(statusIconProto.Icon);
                }
            }

            entryDisplay.Setup(iconTexture, entry.Message, time, time == catalog.LastRecordTime, this);
            CriminalRecordContainer.AddChild(entryDisplay);
            entryDisplay.SetPositionFirst();

            if (i % 2 == 0)
                ((StyleBoxFlat) entryDisplay.PanelOverride!).BackgroundColor = Color.Transparent;
        }
    }

    public void DeleteRecord(int time)
    {
        OnCriminalStatusDelete?.Invoke(time);
    }
}
