// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class RecordListGroup : BoxContainer
{
    public Control RecordContainer;
    public RecordListGroup()
    {
        RobustXamlLoader.Load(this);
        RecordContainer = this;
    }

    public string GroupName { get; private set; } = "";
    private Color _color = Color.White;

    public void Setup(string name, Color? color = null)
    {
        if (color.HasValue)
            _color = color.Value;

        SetGroupName(name);
    }

    public void SetGroupName(string name)
    {
        GroupName = name;
        GroupNameLabel.SetMarkup($"[color={_color.ToHexNoAlpha()}]{GroupName}[/color]");
    }
}
