using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Contractor.UI;

[GenerateTypedNameReferences]
public sealed partial class ContractorHubMenu : BoxContainer
{
    public ContractorHubMenu()
    {
        RobustXamlLoader.Load(this);
    }
}

