using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.UserInterface.Controls;

[GenerateTypedNameReferences]
[Virtual]
public partial class PinnableDefaultWindow : DefaultWindow
{
    public PinnableDefaultWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Opened()
    {
        base.Opened();

        var pinnedButton = PinUISystem.CreateButton(this, CloseButton);

        pinnedButton.OnPressed += _ => PinUISystem.SetPinned(this, pinnedButton.Pressed);
    }
}
