# Service start

- type: entity
  id: SpawnPointCCBartender
  parent: SpawnPointJobBase
  name: CentComm Bartender
  components:
  - type: SpawnPoint
    job_id: CentCommBartender
  - type: Sprite
    layers:
      - state: green
      - state: captain

- type: entity
  id: SpawnPointCCChef
  parent: SpawnPointJobBase
  name: CentComm Chef
  components:
  - type: SpawnPoint
    job_id: CentCommChef
  - type: Sprite
    layers:
      - state: green
      - state: captain

- type: entity
  id: SpawnPointCCJanitor
  parent: SpawnPointJobBase
  name: CentComm Janitor
  components:
  - type: SpawnPoint
    job_id: CentCommJanitor
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCCServiceWorker
  parent: SpawnPointJobBase
  name: CentComm Service Worker
  components:
  - type: SpawnPoint
    job_id: CentCommServiceWorker
  - type: Sprite
    layers:
      - state: green
      - state: captain

- type: entity
  id: SpawnPointCCMaid
  parent: SpawnPointJobBase
  name: CentComm Maid
  components:
  - type: SpawnPoint
    job_id: CentCommMaid
  - type: Sprite
    layers:
      - state: green
      - state: captain

#Service end

- type: entity
  id: SpawnPointSpecOpsLeader
  parent: SpawnPointJobBase
  name: SpecOps Leader
  components:
  - type: SpawnPoint
    job_id: SpecOpsLeader
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentComNanoTrasenAdmiral
  parent: SpawnPointJobBase
  name: CentCom NanoTrasen Admiral
  components:
  - type: SpawnPoint
    job_id: CentComNanoTrasenAdmiral
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentCommNanoTrasenDiplomat
  parent: SpawnPointJobBase
  name: CentComm NanoTrasen Diplomat
  components:
  - type: SpawnPoint
    job_id: CentCommNanoTrasenDiplomat
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentcomFieldOfficer
  parent: SpawnPointJobBase
  name: Centcom Field Officer
  components:
  - type: SpawnPoint
    job_id: CentcomFieldOfficer
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentcommOfficer
  parent: SpawnPointJobBase
  name: Centcomm Officer
  components:
  - type: SpawnPoint
    job_id: CentcommOfficer
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentralCommandOfficial
  parent: SpawnPointJobBase
  name: Centcomm Officer
  components:
  - type: SpawnPoint
    job_id: CentralCommandOfficial
  - type: Sprite
    layers:
      - state: green
      - state: captain
      
- type: entity
  id: SpawnPointCentcommCommunicationsOfficer
  parent: SpawnPointJobBase
  name: CentcommCommunicationsOfficer
  components:
  - type: SpawnPoint
    job_id: CentcommCommunicationsOfficer
  - type: Sprite
    layers:
      - state: green
      - state: captain