name: "Labels: Approve"

on:
  pull_request_target:
    types: [review_request_removed]

permissions: write-all

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - name: check all reviewers
        id: check_approvals
        uses: actions/github-script@v7
        with:
          script: |
            console.log('L:A verby 2255 22022025');
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const requiredApprovals = context.payload.pull_request.requested_reviewers.length;
            const approvedReviews = reviews.filter(review => review.state === 'APPROVED').length;
            if (approvedReviews >= requiredApprovals) {
              console.log('All Reviews Submitted');
            } else {
              console.log('Not All Reviews Submitted');
            }
            return approvedReviews >= requiredApprovals;

      - name: rm labels
        if: steps.check_approvals.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToRemove = ['Status: Needs Review', 'Status: Awaiting Changes'];
            const currentLabels = context.payload.pull_request.labels.map(label => label.name);
            console.log('Current Labels:', currentLabels);
            for (const label of labelsToRemove) {
              if (currentLabels.includes(label)) {
                console.log(`Removing label: ${label}`)
                await github.request("DELETE /repos/{owner}/{repo}/issues/{issue_number}/labels/{name}", {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  name: label,
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
