name: "Labels: Approve"

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - name: check all reviewers
        id: check_approvals
        uses: actions/github-script@v7
        with:
          script: |
            console.log('L:A verby 2255 22022025');
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const requiredApprovals = context.payload.pull_request.requested_reviewers.length;
            const approvedReviews = reviews.filter(review => review.state === 'APPROVED').length;

            return approvedReviews >= requiredApprovals;

      - name: rm labels
        if: steps.check_approvals.outputs.result == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.URPRICE_PAT }}
          labels: |
            Status: Needs Review
            Status: Awaiting Changes
        env:
          URPRICE_PAT: ${{ secrets.URPRICE_PAT }}
