// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.SS220.Experience.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.UiElements;

[GenerateTypedNameReferences]
public sealed partial class ExperienceGroupContainer : BoxContainer
{
    private ProtoId<SkillTreeGroupPrototype>? _groupProto = null;

    private string _name = string.Empty;

    public new string Name
    {
        get => _name;
    }

    public ExperienceGroupContainer()
    {
        RobustXamlLoader.Load(this);

        Margin = ExperienceUiStyleDefinitions.BaseTabLikeThickness;
    }

    /// <summary>
    /// Separate update to boost performance
    /// </summary>
    public void UpdateWithList(IEnumerable<(ProtoId<SkillTreePrototype>, SkillTreeExperienceContainer, FixedPoint4)> skillTrees, ProtoId<SkillTreeGroupPrototype> groupProto)
    {
        SkillTreeContainer.RemoveAllChildren();

        _groupProto = groupProto;
        foreach (var (skillTree, skillInfo, progress) in skillTrees)
        {
            var control = new ExperienceTreeContainer();
            control.SetInfo(skillTree, skillInfo, progress);
            SkillTreeContainer.AddChild(control);
        }
    }

    public void SetGroupName(FormattedMessage message)
    {
        GroupName.SetMessage(message);
        _name = message.ToString();
    }
}
