// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Experience.UiElements;

[GenerateTypedNameReferences]
public sealed partial class RedactableSkillTreeShower : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private ProtoId<SkillTreePrototype> _skillTreeId;
    private SkillTreeExperienceInfo _skillTreeInfo = new();

    private int _maxLevel;
    private List<int> _maxSublevels = new();

    public RedactableSkillTreeShower()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SkillLevel.OnTextEntered += OnSkillLevelChange;
        SkillSublevel.OnTextEntered += OnSkillSublevelChange;
    }

    public void SetSkillTreeInfo(ProtoId<SkillTreePrototype> skillTreeId, in SkillTreeExperienceContainer info)
    {
        if (!_prototype.Resolve(skillTreeId, out var skillTree))
            return;

        _skillTreeId = skillTreeId;
        SkillTreeName.SetMessage(Loc.GetString(skillTree.SkillTreeName));

        _maxLevel = skillTree.SkillTree.Count;
        _maxSublevels = [.. skillTree.SkillTree.Select(x => _prototype.Index(x).LevelInfo.MaximumSublevel)];

        _skillTreeInfo = new(info.Info);

        UpdateLineEdits();
    }

    public (ProtoId<SkillTreePrototype>, SkillTreeExperienceContainer) GetInfo()
    {
        return (_skillTreeId, new(_skillTreeInfo, null));
    }

    private void UpdateLineEdits()
    {
        SkillStudiedCheckBox.Pressed = _skillTreeInfo.SkillStudied;
        SkillLevel.SetText($"{_skillTreeInfo.SkillLevel}/{_maxLevel}");
        SkillSublevel.SetText($"{_skillTreeInfo.SkillSublevel}/{_maxSublevels[_skillTreeInfo.SkillLevel]}");
    }

    private void OnSkillLevelChange(LineEdit.LineEditEventArgs args)
    {
        var actualInput = args.Text.Split('/')[0];

        if (int.TryParse(actualInput, out var result))
        {
            result = Math.Clamp(result, 0, _maxLevel);
            _skillTreeInfo.SkillLevel = result;
        }

        UpdateLineEdits();
    }

    private void OnSkillSublevelChange(LineEdit.LineEditEventArgs args)
    {
        var actualInput = args.Text.Split('/')[0];

        if (int.TryParse(actualInput, out var result))
        {
            result = Math.Clamp(result, 0, _maxSublevels[_skillTreeInfo.SkillLevel]);
            _skillTreeInfo.SkillSublevel = result;
        }

        UpdateLineEdits();
    }
}
